// Code generated by go-swagger; DO NOT EDIT.

package bank

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new bank API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for bank API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetBankBalancesAddress(params *GetBankBalancesAddressParams) (*GetBankBalancesAddressOK, error)

	PostBankAccountsAddressTransfers(params *PostBankAccountsAddressTransfersParams) (*PostBankAccountsAddressTransfersAccepted, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetBankBalancesAddress gets the account balances
*/
func (a *Client) GetBankBalancesAddress(params *GetBankBalancesAddressParams) (*GetBankBalancesAddressOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetBankBalancesAddressParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetBankBalancesAddress",
		Method:             "GET",
		PathPattern:        "/bank/balances/{address}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetBankBalancesAddressReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetBankBalancesAddressOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetBankBalancesAddress: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PostBankAccountsAddressTransfers sends coins from one account to another
*/
func (a *Client) PostBankAccountsAddressTransfers(params *PostBankAccountsAddressTransfersParams) (*PostBankAccountsAddressTransfersAccepted, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostBankAccountsAddressTransfersParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PostBankAccountsAddressTransfers",
		Method:             "POST",
		PathPattern:        "/bank/accounts/{address}/transfers",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostBankAccountsAddressTransfersReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostBankAccountsAddressTransfersAccepted)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostBankAccountsAddressTransfers: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
