// Code generated by go-swagger; DO NOT EDIT.

package wasm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/terra-project/mantle/lcd/models"
)

// GetWasmContractsContractAddressReader is a Reader for the GetWasmContractsContractAddress structure.
type GetWasmContractsContractAddressReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWasmContractsContractAddressReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetWasmContractsContractAddressOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetWasmContractsContractAddressOK creates a GetWasmContractsContractAddressOK with default headers values
func NewGetWasmContractsContractAddressOK() *GetWasmContractsContractAddressOK {
	return &GetWasmContractsContractAddressOK{}
}

/*GetWasmContractsContractAddressOK handles this case with default header values.

OK
*/
type GetWasmContractsContractAddressOK struct {
	Payload *models.ContractInfo
}

func (o *GetWasmContractsContractAddressOK) Error() string {
	return fmt.Sprintf("[GET /wasm/contracts/{contractAddress}][%d] getWasmContractsContractAddressOK  %+v", 200, o.Payload)
}

func (o *GetWasmContractsContractAddressOK) GetPayload() *models.ContractInfo {
	return o.Payload
}

func (o *GetWasmContractsContractAddressOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContractInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
