// Code generated by go-swagger; DO NOT EDIT.

package wasm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/terra-project/mantle-sdk/lcd/models"
)

// NewPostWasmCodesCodeIDParams creates a new PostWasmCodesCodeIDParams object
// with the default values initialized.
func NewPostWasmCodesCodeIDParams() *PostWasmCodesCodeIDParams {
	var ()
	return &PostWasmCodesCodeIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostWasmCodesCodeIDParamsWithTimeout creates a new PostWasmCodesCodeIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostWasmCodesCodeIDParamsWithTimeout(timeout time.Duration) *PostWasmCodesCodeIDParams {
	var ()
	return &PostWasmCodesCodeIDParams{

		timeout: timeout,
	}
}

// NewPostWasmCodesCodeIDParamsWithContext creates a new PostWasmCodesCodeIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostWasmCodesCodeIDParamsWithContext(ctx context.Context) *PostWasmCodesCodeIDParams {
	var ()
	return &PostWasmCodesCodeIDParams{

		Context: ctx,
	}
}

// NewPostWasmCodesCodeIDParamsWithHTTPClient creates a new PostWasmCodesCodeIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostWasmCodesCodeIDParamsWithHTTPClient(client *http.Client) *PostWasmCodesCodeIDParams {
	var ()
	return &PostWasmCodesCodeIDParams{
		HTTPClient: client,
	}
}

/*PostWasmCodesCodeIDParams contains all the parameters to send to the API endpoint
for the post wasm codes code ID operation typically these are written to a http.Request
*/
type PostWasmCodesCodeIDParams struct {

	/*CodeID
	  code ID you want to instantiate

	*/
	CodeID float64
	/*InstantiateContractRequestBody*/
	InstantiateContractRequestBody *models.InstantiateContractReq

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post wasm codes code ID params
func (o *PostWasmCodesCodeIDParams) WithTimeout(timeout time.Duration) *PostWasmCodesCodeIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post wasm codes code ID params
func (o *PostWasmCodesCodeIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post wasm codes code ID params
func (o *PostWasmCodesCodeIDParams) WithContext(ctx context.Context) *PostWasmCodesCodeIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post wasm codes code ID params
func (o *PostWasmCodesCodeIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post wasm codes code ID params
func (o *PostWasmCodesCodeIDParams) WithHTTPClient(client *http.Client) *PostWasmCodesCodeIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post wasm codes code ID params
func (o *PostWasmCodesCodeIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCodeID adds the codeID to the post wasm codes code ID params
func (o *PostWasmCodesCodeIDParams) WithCodeID(codeID float64) *PostWasmCodesCodeIDParams {
	o.SetCodeID(codeID)
	return o
}

// SetCodeID adds the codeId to the post wasm codes code ID params
func (o *PostWasmCodesCodeIDParams) SetCodeID(codeID float64) {
	o.CodeID = codeID
}

// WithInstantiateContractRequestBody adds the instantiateContractRequestBody to the post wasm codes code ID params
func (o *PostWasmCodesCodeIDParams) WithInstantiateContractRequestBody(instantiateContractRequestBody *models.InstantiateContractReq) *PostWasmCodesCodeIDParams {
	o.SetInstantiateContractRequestBody(instantiateContractRequestBody)
	return o
}

// SetInstantiateContractRequestBody adds the instantiateContractRequestBody to the post wasm codes code ID params
func (o *PostWasmCodesCodeIDParams) SetInstantiateContractRequestBody(instantiateContractRequestBody *models.InstantiateContractReq) {
	o.InstantiateContractRequestBody = instantiateContractRequestBody
}

// WriteToRequest writes these params to a swagger request
func (o *PostWasmCodesCodeIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param codeID
	if err := r.SetPathParam("codeID", swag.FormatFloat64(o.CodeID)); err != nil {
		return err
	}

	if o.InstantiateContractRequestBody != nil {
		if err := r.SetBodyParam(o.InstantiateContractRequestBody); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
