// Code generated by go-swagger; DO NOT EDIT.

package wasm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/terra-project/mantle-sdk/lcd/models"
)

// PostWasmContractsContractAddressMigrateReader is a Reader for the PostWasmContractsContractAddressMigrate structure.
type PostWasmContractsContractAddressMigrateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostWasmContractsContractAddressMigrateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostWasmContractsContractAddressMigrateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostWasmContractsContractAddressMigrateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostWasmContractsContractAddressMigrateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostWasmContractsContractAddressMigrateOK creates a PostWasmContractsContractAddressMigrateOK with default headers values
func NewPostWasmContractsContractAddressMigrateOK() *PostWasmContractsContractAddressMigrateOK {
	return &PostWasmContractsContractAddressMigrateOK{}
}

/*PostWasmContractsContractAddressMigrateOK handles this case with default header values.

OK
*/
type PostWasmContractsContractAddressMigrateOK struct {
	Payload *models.StdTx
}

func (o *PostWasmContractsContractAddressMigrateOK) Error() string {
	return fmt.Sprintf("[POST /wasm/contracts/{contractAddress}/migrate][%d] postWasmContractsContractAddressMigrateOK  %+v", 200, o.Payload)
}

func (o *PostWasmContractsContractAddressMigrateOK) GetPayload() *models.StdTx {
	return o.Payload
}

func (o *PostWasmContractsContractAddressMigrateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StdTx)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostWasmContractsContractAddressMigrateBadRequest creates a PostWasmContractsContractAddressMigrateBadRequest with default headers values
func NewPostWasmContractsContractAddressMigrateBadRequest() *PostWasmContractsContractAddressMigrateBadRequest {
	return &PostWasmContractsContractAddressMigrateBadRequest{}
}

/*PostWasmContractsContractAddressMigrateBadRequest handles this case with default header values.

Bad request
*/
type PostWasmContractsContractAddressMigrateBadRequest struct {
}

func (o *PostWasmContractsContractAddressMigrateBadRequest) Error() string {
	return fmt.Sprintf("[POST /wasm/contracts/{contractAddress}/migrate][%d] postWasmContractsContractAddressMigrateBadRequest ", 400)
}

func (o *PostWasmContractsContractAddressMigrateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostWasmContractsContractAddressMigrateInternalServerError creates a PostWasmContractsContractAddressMigrateInternalServerError with default headers values
func NewPostWasmContractsContractAddressMigrateInternalServerError() *PostWasmContractsContractAddressMigrateInternalServerError {
	return &PostWasmContractsContractAddressMigrateInternalServerError{}
}

/*PostWasmContractsContractAddressMigrateInternalServerError handles this case with default header values.

Internal Server Error
*/
type PostWasmContractsContractAddressMigrateInternalServerError struct {
}

func (o *PostWasmContractsContractAddressMigrateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /wasm/contracts/{contractAddress}/migrate][%d] postWasmContractsContractAddressMigrateInternalServerError ", 500)
}

func (o *PostWasmContractsContractAddressMigrateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
