// Code generated by go-swagger; DO NOT EDIT.

package wasm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/terra-project/mantle-sdk/lcd/models"
)

// PostWasmCodesReader is a Reader for the PostWasmCodes structure.
type PostWasmCodesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostWasmCodesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostWasmCodesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostWasmCodesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostWasmCodesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostWasmCodesOK creates a PostWasmCodesOK with default headers values
func NewPostWasmCodesOK() *PostWasmCodesOK {
	return &PostWasmCodesOK{}
}

/*PostWasmCodesOK handles this case with default header values.

OK
*/
type PostWasmCodesOK struct {
	Payload *models.StdTx
}

func (o *PostWasmCodesOK) Error() string {
	return fmt.Sprintf("[POST /wasm/codes][%d] postWasmCodesOK  %+v", 200, o.Payload)
}

func (o *PostWasmCodesOK) GetPayload() *models.StdTx {
	return o.Payload
}

func (o *PostWasmCodesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StdTx)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostWasmCodesBadRequest creates a PostWasmCodesBadRequest with default headers values
func NewPostWasmCodesBadRequest() *PostWasmCodesBadRequest {
	return &PostWasmCodesBadRequest{}
}

/*PostWasmCodesBadRequest handles this case with default header values.

Bad request
*/
type PostWasmCodesBadRequest struct {
}

func (o *PostWasmCodesBadRequest) Error() string {
	return fmt.Sprintf("[POST /wasm/codes][%d] postWasmCodesBadRequest ", 400)
}

func (o *PostWasmCodesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostWasmCodesInternalServerError creates a PostWasmCodesInternalServerError with default headers values
func NewPostWasmCodesInternalServerError() *PostWasmCodesInternalServerError {
	return &PostWasmCodesInternalServerError{}
}

/*PostWasmCodesInternalServerError handles this case with default header values.

Internal Server Error
*/
type PostWasmCodesInternalServerError struct {
}

func (o *PostWasmCodesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /wasm/codes][%d] postWasmCodesInternalServerError ", 500)
}

func (o *PostWasmCodesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
