// Code generated by go-swagger; DO NOT EDIT.

package oracle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOracleVotersValidatorVotesParams creates a new GetOracleVotersValidatorVotesParams object
// with the default values initialized.
func NewGetOracleVotersValidatorVotesParams() *GetOracleVotersValidatorVotesParams {
	var ()
	return &GetOracleVotersValidatorVotesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOracleVotersValidatorVotesParamsWithTimeout creates a new GetOracleVotersValidatorVotesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOracleVotersValidatorVotesParamsWithTimeout(timeout time.Duration) *GetOracleVotersValidatorVotesParams {
	var ()
	return &GetOracleVotersValidatorVotesParams{

		timeout: timeout,
	}
}

// NewGetOracleVotersValidatorVotesParamsWithContext creates a new GetOracleVotersValidatorVotesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOracleVotersValidatorVotesParamsWithContext(ctx context.Context) *GetOracleVotersValidatorVotesParams {
	var ()
	return &GetOracleVotersValidatorVotesParams{

		Context: ctx,
	}
}

// NewGetOracleVotersValidatorVotesParamsWithHTTPClient creates a new GetOracleVotersValidatorVotesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOracleVotersValidatorVotesParamsWithHTTPClient(client *http.Client) *GetOracleVotersValidatorVotesParams {
	var ()
	return &GetOracleVotersValidatorVotesParams{
		HTTPClient: client,
	}
}

/*GetOracleVotersValidatorVotesParams contains all the parameters to send to the API endpoint
for the get oracle voters validator votes operation typically these are written to a http.Request
*/
type GetOracleVotersValidatorVotesParams struct {

	/*Validator*/
	Validator string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get oracle voters validator votes params
func (o *GetOracleVotersValidatorVotesParams) WithTimeout(timeout time.Duration) *GetOracleVotersValidatorVotesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get oracle voters validator votes params
func (o *GetOracleVotersValidatorVotesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get oracle voters validator votes params
func (o *GetOracleVotersValidatorVotesParams) WithContext(ctx context.Context) *GetOracleVotersValidatorVotesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get oracle voters validator votes params
func (o *GetOracleVotersValidatorVotesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get oracle voters validator votes params
func (o *GetOracleVotersValidatorVotesParams) WithHTTPClient(client *http.Client) *GetOracleVotersValidatorVotesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get oracle voters validator votes params
func (o *GetOracleVotersValidatorVotesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithValidator adds the validator to the get oracle voters validator votes params
func (o *GetOracleVotersValidatorVotesParams) WithValidator(validator string) *GetOracleVotersValidatorVotesParams {
	o.SetValidator(validator)
	return o
}

// SetValidator adds the validator to the get oracle voters validator votes params
func (o *GetOracleVotersValidatorVotesParams) SetValidator(validator string) {
	o.Validator = validator
}

// WriteToRequest writes these params to a swagger request
func (o *GetOracleVotersValidatorVotesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param validator
	if err := r.SetPathParam("validator", o.Validator); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
