// Code generated by go-swagger; DO NOT EDIT.

package oracle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOracleDenomsDenomVotesParams creates a new GetOracleDenomsDenomVotesParams object
// with the default values initialized.
func NewGetOracleDenomsDenomVotesParams() *GetOracleDenomsDenomVotesParams {
	var ()
	return &GetOracleDenomsDenomVotesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOracleDenomsDenomVotesParamsWithTimeout creates a new GetOracleDenomsDenomVotesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOracleDenomsDenomVotesParamsWithTimeout(timeout time.Duration) *GetOracleDenomsDenomVotesParams {
	var ()
	return &GetOracleDenomsDenomVotesParams{

		timeout: timeout,
	}
}

// NewGetOracleDenomsDenomVotesParamsWithContext creates a new GetOracleDenomsDenomVotesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOracleDenomsDenomVotesParamsWithContext(ctx context.Context) *GetOracleDenomsDenomVotesParams {
	var ()
	return &GetOracleDenomsDenomVotesParams{

		Context: ctx,
	}
}

// NewGetOracleDenomsDenomVotesParamsWithHTTPClient creates a new GetOracleDenomsDenomVotesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOracleDenomsDenomVotesParamsWithHTTPClient(client *http.Client) *GetOracleDenomsDenomVotesParams {
	var ()
	return &GetOracleDenomsDenomVotesParams{
		HTTPClient: client,
	}
}

/*GetOracleDenomsDenomVotesParams contains all the parameters to send to the API endpoint
for the get oracle denoms denom votes operation typically these are written to a http.Request
*/
type GetOracleDenomsDenomVotesParams struct {

	/*Denom
	  The coin denom to get

	*/
	Denom string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get oracle denoms denom votes params
func (o *GetOracleDenomsDenomVotesParams) WithTimeout(timeout time.Duration) *GetOracleDenomsDenomVotesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get oracle denoms denom votes params
func (o *GetOracleDenomsDenomVotesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get oracle denoms denom votes params
func (o *GetOracleDenomsDenomVotesParams) WithContext(ctx context.Context) *GetOracleDenomsDenomVotesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get oracle denoms denom votes params
func (o *GetOracleDenomsDenomVotesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get oracle denoms denom votes params
func (o *GetOracleDenomsDenomVotesParams) WithHTTPClient(client *http.Client) *GetOracleDenomsDenomVotesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get oracle denoms denom votes params
func (o *GetOracleDenomsDenomVotesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDenom adds the denom to the get oracle denoms denom votes params
func (o *GetOracleDenomsDenomVotesParams) WithDenom(denom string) *GetOracleDenomsDenomVotesParams {
	o.SetDenom(denom)
	return o
}

// SetDenom adds the denom to the get oracle denoms denom votes params
func (o *GetOracleDenomsDenomVotesParams) SetDenom(denom string) {
	o.Denom = denom
}

// WriteToRequest writes these params to a swagger request
func (o *GetOracleDenomsDenomVotesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param denom
	if err := r.SetPathParam("denom", o.Denom); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
