// Code generated by go-swagger; DO NOT EDIT.

package oracle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetOracleVotersValidatorMissReader is a Reader for the GetOracleVotersValidatorMiss structure.
type GetOracleVotersValidatorMissReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOracleVotersValidatorMissReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOracleVotersValidatorMissOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetOracleVotersValidatorMissBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetOracleVotersValidatorMissInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetOracleVotersValidatorMissOK creates a GetOracleVotersValidatorMissOK with default headers values
func NewGetOracleVotersValidatorMissOK() *GetOracleVotersValidatorMissOK {
	return &GetOracleVotersValidatorMissOK{}
}

/*GetOracleVotersValidatorMissOK handles this case with default header values.

OK
*/
type GetOracleVotersValidatorMissOK struct {
	Payload int64
}

func (o *GetOracleVotersValidatorMissOK) Error() string {
	return fmt.Sprintf("[GET /oracle/voters/{validator}/miss][%d] getOracleVotersValidatorMissOK  %+v", 200, o.Payload)
}

func (o *GetOracleVotersValidatorMissOK) GetPayload() int64 {
	return o.Payload
}

func (o *GetOracleVotersValidatorMissOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOracleVotersValidatorMissBadRequest creates a GetOracleVotersValidatorMissBadRequest with default headers values
func NewGetOracleVotersValidatorMissBadRequest() *GetOracleVotersValidatorMissBadRequest {
	return &GetOracleVotersValidatorMissBadRequest{}
}

/*GetOracleVotersValidatorMissBadRequest handles this case with default header values.

Bad Request
*/
type GetOracleVotersValidatorMissBadRequest struct {
}

func (o *GetOracleVotersValidatorMissBadRequest) Error() string {
	return fmt.Sprintf("[GET /oracle/voters/{validator}/miss][%d] getOracleVotersValidatorMissBadRequest ", 400)
}

func (o *GetOracleVotersValidatorMissBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetOracleVotersValidatorMissInternalServerError creates a GetOracleVotersValidatorMissInternalServerError with default headers values
func NewGetOracleVotersValidatorMissInternalServerError() *GetOracleVotersValidatorMissInternalServerError {
	return &GetOracleVotersValidatorMissInternalServerError{}
}

/*GetOracleVotersValidatorMissInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetOracleVotersValidatorMissInternalServerError struct {
}

func (o *GetOracleVotersValidatorMissInternalServerError) Error() string {
	return fmt.Sprintf("[GET /oracle/voters/{validator}/miss][%d] getOracleVotersValidatorMissInternalServerError ", 500)
}

func (o *GetOracleVotersValidatorMissInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
