// Code generated by go-swagger; DO NOT EDIT.

package oracle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOracleDenomsDenomVotesValidatorParams creates a new GetOracleDenomsDenomVotesValidatorParams object
// with the default values initialized.
func NewGetOracleDenomsDenomVotesValidatorParams() *GetOracleDenomsDenomVotesValidatorParams {
	var ()
	return &GetOracleDenomsDenomVotesValidatorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOracleDenomsDenomVotesValidatorParamsWithTimeout creates a new GetOracleDenomsDenomVotesValidatorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOracleDenomsDenomVotesValidatorParamsWithTimeout(timeout time.Duration) *GetOracleDenomsDenomVotesValidatorParams {
	var ()
	return &GetOracleDenomsDenomVotesValidatorParams{

		timeout: timeout,
	}
}

// NewGetOracleDenomsDenomVotesValidatorParamsWithContext creates a new GetOracleDenomsDenomVotesValidatorParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOracleDenomsDenomVotesValidatorParamsWithContext(ctx context.Context) *GetOracleDenomsDenomVotesValidatorParams {
	var ()
	return &GetOracleDenomsDenomVotesValidatorParams{

		Context: ctx,
	}
}

// NewGetOracleDenomsDenomVotesValidatorParamsWithHTTPClient creates a new GetOracleDenomsDenomVotesValidatorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOracleDenomsDenomVotesValidatorParamsWithHTTPClient(client *http.Client) *GetOracleDenomsDenomVotesValidatorParams {
	var ()
	return &GetOracleDenomsDenomVotesValidatorParams{
		HTTPClient: client,
	}
}

/*GetOracleDenomsDenomVotesValidatorParams contains all the parameters to send to the API endpoint
for the get oracle denoms denom votes validator operation typically these are written to a http.Request
*/
type GetOracleDenomsDenomVotesValidatorParams struct {

	/*Denom
	  The coin denom to get

	*/
	Denom string
	/*Validator*/
	Validator string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get oracle denoms denom votes validator params
func (o *GetOracleDenomsDenomVotesValidatorParams) WithTimeout(timeout time.Duration) *GetOracleDenomsDenomVotesValidatorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get oracle denoms denom votes validator params
func (o *GetOracleDenomsDenomVotesValidatorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get oracle denoms denom votes validator params
func (o *GetOracleDenomsDenomVotesValidatorParams) WithContext(ctx context.Context) *GetOracleDenomsDenomVotesValidatorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get oracle denoms denom votes validator params
func (o *GetOracleDenomsDenomVotesValidatorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get oracle denoms denom votes validator params
func (o *GetOracleDenomsDenomVotesValidatorParams) WithHTTPClient(client *http.Client) *GetOracleDenomsDenomVotesValidatorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get oracle denoms denom votes validator params
func (o *GetOracleDenomsDenomVotesValidatorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDenom adds the denom to the get oracle denoms denom votes validator params
func (o *GetOracleDenomsDenomVotesValidatorParams) WithDenom(denom string) *GetOracleDenomsDenomVotesValidatorParams {
	o.SetDenom(denom)
	return o
}

// SetDenom adds the denom to the get oracle denoms denom votes validator params
func (o *GetOracleDenomsDenomVotesValidatorParams) SetDenom(denom string) {
	o.Denom = denom
}

// WithValidator adds the validator to the get oracle denoms denom votes validator params
func (o *GetOracleDenomsDenomVotesValidatorParams) WithValidator(validator string) *GetOracleDenomsDenomVotesValidatorParams {
	o.SetValidator(validator)
	return o
}

// SetValidator adds the validator to the get oracle denoms denom votes validator params
func (o *GetOracleDenomsDenomVotesValidatorParams) SetValidator(validator string) {
	o.Validator = validator
}

// WriteToRequest writes these params to a swagger request
func (o *GetOracleDenomsDenomVotesValidatorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param denom
	if err := r.SetPathParam("denom", o.Denom); err != nil {
		return err
	}

	// path param validator
	if err := r.SetPathParam("validator", o.Validator); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
