// Code generated by go-swagger; DO NOT EDIT.

package oracle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOracleDenomsActivesParams creates a new GetOracleDenomsActivesParams object
// with the default values initialized.
func NewGetOracleDenomsActivesParams() *GetOracleDenomsActivesParams {

	return &GetOracleDenomsActivesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOracleDenomsActivesParamsWithTimeout creates a new GetOracleDenomsActivesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOracleDenomsActivesParamsWithTimeout(timeout time.Duration) *GetOracleDenomsActivesParams {

	return &GetOracleDenomsActivesParams{

		timeout: timeout,
	}
}

// NewGetOracleDenomsActivesParamsWithContext creates a new GetOracleDenomsActivesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOracleDenomsActivesParamsWithContext(ctx context.Context) *GetOracleDenomsActivesParams {

	return &GetOracleDenomsActivesParams{

		Context: ctx,
	}
}

// NewGetOracleDenomsActivesParamsWithHTTPClient creates a new GetOracleDenomsActivesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOracleDenomsActivesParamsWithHTTPClient(client *http.Client) *GetOracleDenomsActivesParams {

	return &GetOracleDenomsActivesParams{
		HTTPClient: client,
	}
}

/*GetOracleDenomsActivesParams contains all the parameters to send to the API endpoint
for the get oracle denoms actives operation typically these are written to a http.Request
*/
type GetOracleDenomsActivesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get oracle denoms actives params
func (o *GetOracleDenomsActivesParams) WithTimeout(timeout time.Duration) *GetOracleDenomsActivesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get oracle denoms actives params
func (o *GetOracleDenomsActivesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get oracle denoms actives params
func (o *GetOracleDenomsActivesParams) WithContext(ctx context.Context) *GetOracleDenomsActivesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get oracle denoms actives params
func (o *GetOracleDenomsActivesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get oracle denoms actives params
func (o *GetOracleDenomsActivesParams) WithHTTPClient(client *http.Client) *GetOracleDenomsActivesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get oracle denoms actives params
func (o *GetOracleDenomsActivesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetOracleDenomsActivesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
