// Code generated by go-swagger; DO NOT EDIT.

package oracle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/terra-project/mantle-sdk/lcd/models"
)

// NewPostOracleVotersValidatorAggregateVoteParams creates a new PostOracleVotersValidatorAggregateVoteParams object
// with the default values initialized.
func NewPostOracleVotersValidatorAggregateVoteParams() *PostOracleVotersValidatorAggregateVoteParams {
	var ()
	return &PostOracleVotersValidatorAggregateVoteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostOracleVotersValidatorAggregateVoteParamsWithTimeout creates a new PostOracleVotersValidatorAggregateVoteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostOracleVotersValidatorAggregateVoteParamsWithTimeout(timeout time.Duration) *PostOracleVotersValidatorAggregateVoteParams {
	var ()
	return &PostOracleVotersValidatorAggregateVoteParams{

		timeout: timeout,
	}
}

// NewPostOracleVotersValidatorAggregateVoteParamsWithContext creates a new PostOracleVotersValidatorAggregateVoteParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostOracleVotersValidatorAggregateVoteParamsWithContext(ctx context.Context) *PostOracleVotersValidatorAggregateVoteParams {
	var ()
	return &PostOracleVotersValidatorAggregateVoteParams{

		Context: ctx,
	}
}

// NewPostOracleVotersValidatorAggregateVoteParamsWithHTTPClient creates a new PostOracleVotersValidatorAggregateVoteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostOracleVotersValidatorAggregateVoteParamsWithHTTPClient(client *http.Client) *PostOracleVotersValidatorAggregateVoteParams {
	var ()
	return &PostOracleVotersValidatorAggregateVoteParams{
		HTTPClient: client,
	}
}

/*PostOracleVotersValidatorAggregateVoteParams contains all the parameters to send to the API endpoint
for the post oracle voters validator aggregate vote operation typically these are written to a http.Request
*/
type PostOracleVotersValidatorAggregateVoteParams struct {

	/*AggregateVoteRequestBody*/
	AggregateVoteRequestBody *models.AggregateVoteReq
	/*Validator
	  oracle operator

	*/
	Validator string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post oracle voters validator aggregate vote params
func (o *PostOracleVotersValidatorAggregateVoteParams) WithTimeout(timeout time.Duration) *PostOracleVotersValidatorAggregateVoteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post oracle voters validator aggregate vote params
func (o *PostOracleVotersValidatorAggregateVoteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post oracle voters validator aggregate vote params
func (o *PostOracleVotersValidatorAggregateVoteParams) WithContext(ctx context.Context) *PostOracleVotersValidatorAggregateVoteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post oracle voters validator aggregate vote params
func (o *PostOracleVotersValidatorAggregateVoteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post oracle voters validator aggregate vote params
func (o *PostOracleVotersValidatorAggregateVoteParams) WithHTTPClient(client *http.Client) *PostOracleVotersValidatorAggregateVoteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post oracle voters validator aggregate vote params
func (o *PostOracleVotersValidatorAggregateVoteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAggregateVoteRequestBody adds the aggregateVoteRequestBody to the post oracle voters validator aggregate vote params
func (o *PostOracleVotersValidatorAggregateVoteParams) WithAggregateVoteRequestBody(aggregateVoteRequestBody *models.AggregateVoteReq) *PostOracleVotersValidatorAggregateVoteParams {
	o.SetAggregateVoteRequestBody(aggregateVoteRequestBody)
	return o
}

// SetAggregateVoteRequestBody adds the aggregateVoteRequestBody to the post oracle voters validator aggregate vote params
func (o *PostOracleVotersValidatorAggregateVoteParams) SetAggregateVoteRequestBody(aggregateVoteRequestBody *models.AggregateVoteReq) {
	o.AggregateVoteRequestBody = aggregateVoteRequestBody
}

// WithValidator adds the validator to the post oracle voters validator aggregate vote params
func (o *PostOracleVotersValidatorAggregateVoteParams) WithValidator(validator string) *PostOracleVotersValidatorAggregateVoteParams {
	o.SetValidator(validator)
	return o
}

// SetValidator adds the validator to the post oracle voters validator aggregate vote params
func (o *PostOracleVotersValidatorAggregateVoteParams) SetValidator(validator string) {
	o.Validator = validator
}

// WriteToRequest writes these params to a swagger request
func (o *PostOracleVotersValidatorAggregateVoteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AggregateVoteRequestBody != nil {
		if err := r.SetBodyParam(o.AggregateVoteRequestBody); err != nil {
			return err
		}
	}

	// path param validator
	if err := r.SetPathParam("validator", o.Validator); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
