// Code generated by go-swagger; DO NOT EDIT.

package mint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetMintingAnnualProvisionsReader is a Reader for the GetMintingAnnualProvisions structure.
type GetMintingAnnualProvisionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMintingAnnualProvisionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMintingAnnualProvisionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetMintingAnnualProvisionsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetMintingAnnualProvisionsOK creates a GetMintingAnnualProvisionsOK with default headers values
func NewGetMintingAnnualProvisionsOK() *GetMintingAnnualProvisionsOK {
	return &GetMintingAnnualProvisionsOK{}
}

/*GetMintingAnnualProvisionsOK handles this case with default header values.

OK
*/
type GetMintingAnnualProvisionsOK struct {
	Payload *GetMintingAnnualProvisionsOKBody
}

func (o *GetMintingAnnualProvisionsOK) Error() string {
	return fmt.Sprintf("[GET /minting/annual-provisions][%d] getMintingAnnualProvisionsOK  %+v", 200, o.Payload)
}

func (o *GetMintingAnnualProvisionsOK) GetPayload() *GetMintingAnnualProvisionsOKBody {
	return o.Payload
}

func (o *GetMintingAnnualProvisionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetMintingAnnualProvisionsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMintingAnnualProvisionsInternalServerError creates a GetMintingAnnualProvisionsInternalServerError with default headers values
func NewGetMintingAnnualProvisionsInternalServerError() *GetMintingAnnualProvisionsInternalServerError {
	return &GetMintingAnnualProvisionsInternalServerError{}
}

/*GetMintingAnnualProvisionsInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetMintingAnnualProvisionsInternalServerError struct {
}

func (o *GetMintingAnnualProvisionsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /minting/annual-provisions][%d] getMintingAnnualProvisionsInternalServerError ", 500)
}

func (o *GetMintingAnnualProvisionsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetMintingAnnualProvisionsOKBody get minting annual provisions o k body
swagger:model GetMintingAnnualProvisionsOKBody
*/
type GetMintingAnnualProvisionsOKBody struct {

	// height
	Height string `json:"height,omitempty"`

	// result
	Result string `json:"result,omitempty"`
}

// Validate validates this get minting annual provisions o k body
func (o *GetMintingAnnualProvisionsOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetMintingAnnualProvisionsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetMintingAnnualProvisionsOKBody) UnmarshalBinary(b []byte) error {
	var res GetMintingAnnualProvisionsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
