// Code generated by go-swagger; DO NOT EDIT.

package mint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetMintingParametersReader is a Reader for the GetMintingParameters structure.
type GetMintingParametersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMintingParametersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMintingParametersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetMintingParametersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetMintingParametersOK creates a GetMintingParametersOK with default headers values
func NewGetMintingParametersOK() *GetMintingParametersOK {
	return &GetMintingParametersOK{}
}

/*GetMintingParametersOK handles this case with default header values.

OK
*/
type GetMintingParametersOK struct {
	Payload *GetMintingParametersOKBody
}

func (o *GetMintingParametersOK) Error() string {
	return fmt.Sprintf("[GET /minting/parameters][%d] getMintingParametersOK  %+v", 200, o.Payload)
}

func (o *GetMintingParametersOK) GetPayload() *GetMintingParametersOKBody {
	return o.Payload
}

func (o *GetMintingParametersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetMintingParametersOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMintingParametersInternalServerError creates a GetMintingParametersInternalServerError with default headers values
func NewGetMintingParametersInternalServerError() *GetMintingParametersInternalServerError {
	return &GetMintingParametersInternalServerError{}
}

/*GetMintingParametersInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetMintingParametersInternalServerError struct {
}

func (o *GetMintingParametersInternalServerError) Error() string {
	return fmt.Sprintf("[GET /minting/parameters][%d] getMintingParametersInternalServerError ", 500)
}

func (o *GetMintingParametersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetMintingParametersOKBody get minting parameters o k body
swagger:model GetMintingParametersOKBody
*/
type GetMintingParametersOKBody struct {

	// height
	Height string `json:"height,omitempty"`

	// result
	Result *GetMintingParametersOKBodyResult `json:"result,omitempty"`
}

// Validate validates this get minting parameters o k body
func (o *GetMintingParametersOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetMintingParametersOKBody) validateResult(formats strfmt.Registry) error {

	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getMintingParametersOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetMintingParametersOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetMintingParametersOKBody) UnmarshalBinary(b []byte) error {
	var res GetMintingParametersOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetMintingParametersOKBodyResult get minting parameters o k body result
swagger:model GetMintingParametersOKBodyResult
*/
type GetMintingParametersOKBodyResult struct {

	// blocks per year
	BlocksPerYear string `json:"blocks_per_year,omitempty"`

	// goal bonded
	GoalBonded string `json:"goal_bonded,omitempty"`

	// inflation max
	InflationMax string `json:"inflation_max,omitempty"`

	// inflation min
	InflationMin string `json:"inflation_min,omitempty"`

	// inflation rate change
	InflationRateChange string `json:"inflation_rate_change,omitempty"`

	// mint denom
	MintDenom string `json:"mint_denom,omitempty"`
}

// Validate validates this get minting parameters o k body result
func (o *GetMintingParametersOKBodyResult) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetMintingParametersOKBodyResult) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetMintingParametersOKBodyResult) UnmarshalBinary(b []byte) error {
	var res GetMintingParametersOKBodyResult
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
