// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTxsHashParams creates a new GetTxsHashParams object
// with the default values initialized.
func NewGetTxsHashParams() *GetTxsHashParams {
	var ()
	return &GetTxsHashParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTxsHashParamsWithTimeout creates a new GetTxsHashParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTxsHashParamsWithTimeout(timeout time.Duration) *GetTxsHashParams {
	var ()
	return &GetTxsHashParams{

		timeout: timeout,
	}
}

// NewGetTxsHashParamsWithContext creates a new GetTxsHashParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTxsHashParamsWithContext(ctx context.Context) *GetTxsHashParams {
	var ()
	return &GetTxsHashParams{

		Context: ctx,
	}
}

// NewGetTxsHashParamsWithHTTPClient creates a new GetTxsHashParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTxsHashParamsWithHTTPClient(client *http.Client) *GetTxsHashParams {
	var ()
	return &GetTxsHashParams{
		HTTPClient: client,
	}
}

/*GetTxsHashParams contains all the parameters to send to the API endpoint
for the get txs hash operation typically these are written to a http.Request
*/
type GetTxsHashParams struct {

	/*Hash
	  Tx hash

	*/
	Hash string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get txs hash params
func (o *GetTxsHashParams) WithTimeout(timeout time.Duration) *GetTxsHashParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get txs hash params
func (o *GetTxsHashParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get txs hash params
func (o *GetTxsHashParams) WithContext(ctx context.Context) *GetTxsHashParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get txs hash params
func (o *GetTxsHashParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get txs hash params
func (o *GetTxsHashParams) WithHTTPClient(client *http.Client) *GetTxsHashParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get txs hash params
func (o *GetTxsHashParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHash adds the hash to the get txs hash params
func (o *GetTxsHashParams) WithHash(hash string) *GetTxsHashParams {
	o.SetHash(hash)
	return o
}

// SetHash adds the hash to the get txs hash params
func (o *GetTxsHashParams) SetHash(hash string) {
	o.Hash = hash
}

// WriteToRequest writes these params to a swagger request
func (o *GetTxsHashParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param hash
	if err := r.SetPathParam("hash", o.Hash); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
