// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/terra-project/mantle-sdk/lcd/models"
)

// GetTxsHashReader is a Reader for the GetTxsHash structure.
type GetTxsHashReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTxsHashReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTxsHashOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetTxsHashInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTxsHashOK creates a GetTxsHashOK with default headers values
func NewGetTxsHashOK() *GetTxsHashOK {
	return &GetTxsHashOK{}
}

/*GetTxsHashOK handles this case with default header values.

Tx with the provided hash
*/
type GetTxsHashOK struct {
	Payload *models.TxQuery
}

func (o *GetTxsHashOK) Error() string {
	return fmt.Sprintf("[GET /txs/{hash}][%d] getTxsHashOK  %+v", 200, o.Payload)
}

func (o *GetTxsHashOK) GetPayload() *models.TxQuery {
	return o.Payload
}

func (o *GetTxsHashOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TxQuery)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTxsHashInternalServerError creates a GetTxsHashInternalServerError with default headers values
func NewGetTxsHashInternalServerError() *GetTxsHashInternalServerError {
	return &GetTxsHashInternalServerError{}
}

/*GetTxsHashInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetTxsHashInternalServerError struct {
}

func (o *GetTxsHashInternalServerError) Error() string {
	return fmt.Sprintf("[GET /txs/{hash}][%d] getTxsHashInternalServerError ", 500)
}

func (o *GetTxsHashInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
