// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostTxsEncodeParams creates a new PostTxsEncodeParams object
// with the default values initialized.
func NewPostTxsEncodeParams() *PostTxsEncodeParams {
	var ()
	return &PostTxsEncodeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostTxsEncodeParamsWithTimeout creates a new PostTxsEncodeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostTxsEncodeParamsWithTimeout(timeout time.Duration) *PostTxsEncodeParams {
	var ()
	return &PostTxsEncodeParams{

		timeout: timeout,
	}
}

// NewPostTxsEncodeParamsWithContext creates a new PostTxsEncodeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostTxsEncodeParamsWithContext(ctx context.Context) *PostTxsEncodeParams {
	var ()
	return &PostTxsEncodeParams{

		Context: ctx,
	}
}

// NewPostTxsEncodeParamsWithHTTPClient creates a new PostTxsEncodeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostTxsEncodeParamsWithHTTPClient(client *http.Client) *PostTxsEncodeParams {
	var ()
	return &PostTxsEncodeParams{
		HTTPClient: client,
	}
}

/*PostTxsEncodeParams contains all the parameters to send to the API endpoint
for the post txs encode operation typically these are written to a http.Request
*/
type PostTxsEncodeParams struct {

	/*Tx
	  The tx to encode

	*/
	Tx PostTxsEncodeBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post txs encode params
func (o *PostTxsEncodeParams) WithTimeout(timeout time.Duration) *PostTxsEncodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post txs encode params
func (o *PostTxsEncodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post txs encode params
func (o *PostTxsEncodeParams) WithContext(ctx context.Context) *PostTxsEncodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post txs encode params
func (o *PostTxsEncodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post txs encode params
func (o *PostTxsEncodeParams) WithHTTPClient(client *http.Client) *PostTxsEncodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post txs encode params
func (o *PostTxsEncodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTx adds the tx to the post txs encode params
func (o *PostTxsEncodeParams) WithTx(tx PostTxsEncodeBody) *PostTxsEncodeParams {
	o.SetTx(tx)
	return o
}

// SetTx adds the tx to the post txs encode params
func (o *PostTxsEncodeParams) SetTx(tx PostTxsEncodeBody) {
	o.Tx = tx
}

// WriteToRequest writes these params to a swagger request
func (o *PostTxsEncodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Tx); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
