// Code generated by go-swagger; DO NOT EDIT.

package staking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/terra-project/mantle-sdk/lcd/models"
)

// GetStakingDelegatorsDelegatorAddrUnbondingDelegationsReader is a Reader for the GetStakingDelegatorsDelegatorAddrUnbondingDelegations structure.
type GetStakingDelegatorsDelegatorAddrUnbondingDelegationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStakingDelegatorsDelegatorAddrUnbondingDelegationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStakingDelegatorsDelegatorAddrUnbondingDelegationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetStakingDelegatorsDelegatorAddrUnbondingDelegationsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetStakingDelegatorsDelegatorAddrUnbondingDelegationsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetStakingDelegatorsDelegatorAddrUnbondingDelegationsOK creates a GetStakingDelegatorsDelegatorAddrUnbondingDelegationsOK with default headers values
func NewGetStakingDelegatorsDelegatorAddrUnbondingDelegationsOK() *GetStakingDelegatorsDelegatorAddrUnbondingDelegationsOK {
	return &GetStakingDelegatorsDelegatorAddrUnbondingDelegationsOK{}
}

/*GetStakingDelegatorsDelegatorAddrUnbondingDelegationsOK handles this case with default header values.

OK
*/
type GetStakingDelegatorsDelegatorAddrUnbondingDelegationsOK struct {
	Payload *GetStakingDelegatorsDelegatorAddrUnbondingDelegationsOKBody
}

func (o *GetStakingDelegatorsDelegatorAddrUnbondingDelegationsOK) Error() string {
	return fmt.Sprintf("[GET /staking/delegators/{delegatorAddr}/unbonding_delegations][%d] getStakingDelegatorsDelegatorAddrUnbondingDelegationsOK  %+v", 200, o.Payload)
}

func (o *GetStakingDelegatorsDelegatorAddrUnbondingDelegationsOK) GetPayload() *GetStakingDelegatorsDelegatorAddrUnbondingDelegationsOKBody {
	return o.Payload
}

func (o *GetStakingDelegatorsDelegatorAddrUnbondingDelegationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetStakingDelegatorsDelegatorAddrUnbondingDelegationsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStakingDelegatorsDelegatorAddrUnbondingDelegationsBadRequest creates a GetStakingDelegatorsDelegatorAddrUnbondingDelegationsBadRequest with default headers values
func NewGetStakingDelegatorsDelegatorAddrUnbondingDelegationsBadRequest() *GetStakingDelegatorsDelegatorAddrUnbondingDelegationsBadRequest {
	return &GetStakingDelegatorsDelegatorAddrUnbondingDelegationsBadRequest{}
}

/*GetStakingDelegatorsDelegatorAddrUnbondingDelegationsBadRequest handles this case with default header values.

Invalid delegator address
*/
type GetStakingDelegatorsDelegatorAddrUnbondingDelegationsBadRequest struct {
}

func (o *GetStakingDelegatorsDelegatorAddrUnbondingDelegationsBadRequest) Error() string {
	return fmt.Sprintf("[GET /staking/delegators/{delegatorAddr}/unbonding_delegations][%d] getStakingDelegatorsDelegatorAddrUnbondingDelegationsBadRequest ", 400)
}

func (o *GetStakingDelegatorsDelegatorAddrUnbondingDelegationsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetStakingDelegatorsDelegatorAddrUnbondingDelegationsInternalServerError creates a GetStakingDelegatorsDelegatorAddrUnbondingDelegationsInternalServerError with default headers values
func NewGetStakingDelegatorsDelegatorAddrUnbondingDelegationsInternalServerError() *GetStakingDelegatorsDelegatorAddrUnbondingDelegationsInternalServerError {
	return &GetStakingDelegatorsDelegatorAddrUnbondingDelegationsInternalServerError{}
}

/*GetStakingDelegatorsDelegatorAddrUnbondingDelegationsInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetStakingDelegatorsDelegatorAddrUnbondingDelegationsInternalServerError struct {
}

func (o *GetStakingDelegatorsDelegatorAddrUnbondingDelegationsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /staking/delegators/{delegatorAddr}/unbonding_delegations][%d] getStakingDelegatorsDelegatorAddrUnbondingDelegationsInternalServerError ", 500)
}

func (o *GetStakingDelegatorsDelegatorAddrUnbondingDelegationsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetStakingDelegatorsDelegatorAddrUnbondingDelegationsOKBody get staking delegators delegator addr unbonding delegations o k body
swagger:model GetStakingDelegatorsDelegatorAddrUnbondingDelegationsOKBody
*/
type GetStakingDelegatorsDelegatorAddrUnbondingDelegationsOKBody struct {

	// height
	Height string `json:"height,omitempty"`

	// result
	Result []*models.UnbondingDelegation `json:"result"`
}

// Validate validates this get staking delegators delegator addr unbonding delegations o k body
func (o *GetStakingDelegatorsDelegatorAddrUnbondingDelegationsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetStakingDelegatorsDelegatorAddrUnbondingDelegationsOKBody) validateResult(formats strfmt.Registry) error {

	if swag.IsZero(o.Result) { // not required
		return nil
	}

	for i := 0; i < len(o.Result); i++ {
		if swag.IsZero(o.Result[i]) { // not required
			continue
		}

		if o.Result[i] != nil {
			if err := o.Result[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getStakingDelegatorsDelegatorAddrUnbondingDelegationsOK" + "." + "result" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetStakingDelegatorsDelegatorAddrUnbondingDelegationsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetStakingDelegatorsDelegatorAddrUnbondingDelegationsOKBody) UnmarshalBinary(b []byte) error {
	var res GetStakingDelegatorsDelegatorAddrUnbondingDelegationsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
