// Code generated by go-swagger; DO NOT EDIT.

package staking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams creates a new GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams object
// with the default values initialized.
func NewGetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams() *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams {
	var ()
	return &GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParamsWithTimeout creates a new GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParamsWithTimeout(timeout time.Duration) *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams {
	var ()
	return &GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams{

		timeout: timeout,
	}
}

// NewGetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParamsWithContext creates a new GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParamsWithContext(ctx context.Context) *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams {
	var ()
	return &GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams{

		Context: ctx,
	}
}

// NewGetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParamsWithHTTPClient creates a new GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParamsWithHTTPClient(client *http.Client) *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams {
	var ()
	return &GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams{
		HTTPClient: client,
	}
}

/*GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams contains all the parameters to send to the API endpoint
for the get staking delegators delegator addr delegations validator addr operation typically these are written to a http.Request
*/
type GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams struct {

	/*DelegatorAddr
	  Bech32 AccAddress of Delegator

	*/
	DelegatorAddr string
	/*ValidatorAddr
	  Bech32 OperatorAddress of validator

	*/
	ValidatorAddr string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get staking delegators delegator addr delegations validator addr params
func (o *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams) WithTimeout(timeout time.Duration) *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get staking delegators delegator addr delegations validator addr params
func (o *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get staking delegators delegator addr delegations validator addr params
func (o *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams) WithContext(ctx context.Context) *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get staking delegators delegator addr delegations validator addr params
func (o *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get staking delegators delegator addr delegations validator addr params
func (o *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams) WithHTTPClient(client *http.Client) *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get staking delegators delegator addr delegations validator addr params
func (o *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDelegatorAddr adds the delegatorAddr to the get staking delegators delegator addr delegations validator addr params
func (o *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams) WithDelegatorAddr(delegatorAddr string) *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams {
	o.SetDelegatorAddr(delegatorAddr)
	return o
}

// SetDelegatorAddr adds the delegatorAddr to the get staking delegators delegator addr delegations validator addr params
func (o *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams) SetDelegatorAddr(delegatorAddr string) {
	o.DelegatorAddr = delegatorAddr
}

// WithValidatorAddr adds the validatorAddr to the get staking delegators delegator addr delegations validator addr params
func (o *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams) WithValidatorAddr(validatorAddr string) *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams {
	o.SetValidatorAddr(validatorAddr)
	return o
}

// SetValidatorAddr adds the validatorAddr to the get staking delegators delegator addr delegations validator addr params
func (o *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams) SetValidatorAddr(validatorAddr string) {
	o.ValidatorAddr = validatorAddr
}

// WriteToRequest writes these params to a swagger request
func (o *GetStakingDelegatorsDelegatorAddrDelegationsValidatorAddrParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param delegatorAddr
	if err := r.SetPathParam("delegatorAddr", o.DelegatorAddr); err != nil {
		return err
	}

	// path param validatorAddr
	if err := r.SetPathParam("validatorAddr", o.ValidatorAddr); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
