// Code generated by go-swagger; DO NOT EDIT.

package market

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/terra-project/mantle-sdk/lcd/models"
)

// PostMarketSwapReader is a Reader for the PostMarketSwap structure.
type PostMarketSwapReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostMarketSwapReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostMarketSwapOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewPostMarketSwapInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostMarketSwapOK creates a PostMarketSwapOK with default headers values
func NewPostMarketSwapOK() *PostMarketSwapOK {
	return &PostMarketSwapOK{}
}

/*PostMarketSwapOK handles this case with default header values.

OK
*/
type PostMarketSwapOK struct {
	Payload *models.StdTx
}

func (o *PostMarketSwapOK) Error() string {
	return fmt.Sprintf("[POST /market/swap][%d] postMarketSwapOK  %+v", 200, o.Payload)
}

func (o *PostMarketSwapOK) GetPayload() *models.StdTx {
	return o.Payload
}

func (o *PostMarketSwapOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StdTx)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostMarketSwapInternalServerError creates a PostMarketSwapInternalServerError with default headers values
func NewPostMarketSwapInternalServerError() *PostMarketSwapInternalServerError {
	return &PostMarketSwapInternalServerError{}
}

/*PostMarketSwapInternalServerError handles this case with default header values.

Internal Server Error
*/
type PostMarketSwapInternalServerError struct {
}

func (o *PostMarketSwapInternalServerError) Error() string {
	return fmt.Sprintf("[POST /market/swap][%d] postMarketSwapInternalServerError ", 500)
}

func (o *PostMarketSwapInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
