// Code generated by go-swagger; DO NOT EDIT.

package slashing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSlashingParametersParams creates a new GetSlashingParametersParams object
// with the default values initialized.
func NewGetSlashingParametersParams() *GetSlashingParametersParams {

	return &GetSlashingParametersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSlashingParametersParamsWithTimeout creates a new GetSlashingParametersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSlashingParametersParamsWithTimeout(timeout time.Duration) *GetSlashingParametersParams {

	return &GetSlashingParametersParams{

		timeout: timeout,
	}
}

// NewGetSlashingParametersParamsWithContext creates a new GetSlashingParametersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSlashingParametersParamsWithContext(ctx context.Context) *GetSlashingParametersParams {

	return &GetSlashingParametersParams{

		Context: ctx,
	}
}

// NewGetSlashingParametersParamsWithHTTPClient creates a new GetSlashingParametersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSlashingParametersParamsWithHTTPClient(client *http.Client) *GetSlashingParametersParams {

	return &GetSlashingParametersParams{
		HTTPClient: client,
	}
}

/*GetSlashingParametersParams contains all the parameters to send to the API endpoint
for the get slashing parameters operation typically these are written to a http.Request
*/
type GetSlashingParametersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get slashing parameters params
func (o *GetSlashingParametersParams) WithTimeout(timeout time.Duration) *GetSlashingParametersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get slashing parameters params
func (o *GetSlashingParametersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get slashing parameters params
func (o *GetSlashingParametersParams) WithContext(ctx context.Context) *GetSlashingParametersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get slashing parameters params
func (o *GetSlashingParametersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get slashing parameters params
func (o *GetSlashingParametersParams) WithHTTPClient(client *http.Client) *GetSlashingParametersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get slashing parameters params
func (o *GetSlashingParametersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSlashingParametersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
