// Code generated by go-swagger; DO NOT EDIT.

package governance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/terra-project/mantle-sdk/lcd/models"
)

// GetGovProposalsProposalIDVotesVoterReader is a Reader for the GetGovProposalsProposalIDVotesVoter structure.
type GetGovProposalsProposalIDVotesVoterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGovProposalsProposalIDVotesVoterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGovProposalsProposalIDVotesVoterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetGovProposalsProposalIDVotesVoterBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetGovProposalsProposalIDVotesVoterNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetGovProposalsProposalIDVotesVoterInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetGovProposalsProposalIDVotesVoterOK creates a GetGovProposalsProposalIDVotesVoterOK with default headers values
func NewGetGovProposalsProposalIDVotesVoterOK() *GetGovProposalsProposalIDVotesVoterOK {
	return &GetGovProposalsProposalIDVotesVoterOK{}
}

/*GetGovProposalsProposalIDVotesVoterOK handles this case with default header values.

OK
*/
type GetGovProposalsProposalIDVotesVoterOK struct {
	Payload *models.Vote
}

func (o *GetGovProposalsProposalIDVotesVoterOK) Error() string {
	return fmt.Sprintf("[GET /gov/proposals/{proposalId}/votes/{voter}][%d] getGovProposalsProposalIdVotesVoterOK  %+v", 200, o.Payload)
}

func (o *GetGovProposalsProposalIDVotesVoterOK) GetPayload() *models.Vote {
	return o.Payload
}

func (o *GetGovProposalsProposalIDVotesVoterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Vote)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGovProposalsProposalIDVotesVoterBadRequest creates a GetGovProposalsProposalIDVotesVoterBadRequest with default headers values
func NewGetGovProposalsProposalIDVotesVoterBadRequest() *GetGovProposalsProposalIDVotesVoterBadRequest {
	return &GetGovProposalsProposalIDVotesVoterBadRequest{}
}

/*GetGovProposalsProposalIDVotesVoterBadRequest handles this case with default header values.

Invalid proposal id or voter address
*/
type GetGovProposalsProposalIDVotesVoterBadRequest struct {
}

func (o *GetGovProposalsProposalIDVotesVoterBadRequest) Error() string {
	return fmt.Sprintf("[GET /gov/proposals/{proposalId}/votes/{voter}][%d] getGovProposalsProposalIdVotesVoterBadRequest ", 400)
}

func (o *GetGovProposalsProposalIDVotesVoterBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetGovProposalsProposalIDVotesVoterNotFound creates a GetGovProposalsProposalIDVotesVoterNotFound with default headers values
func NewGetGovProposalsProposalIDVotesVoterNotFound() *GetGovProposalsProposalIDVotesVoterNotFound {
	return &GetGovProposalsProposalIDVotesVoterNotFound{}
}

/*GetGovProposalsProposalIDVotesVoterNotFound handles this case with default header values.

Found no vote
*/
type GetGovProposalsProposalIDVotesVoterNotFound struct {
}

func (o *GetGovProposalsProposalIDVotesVoterNotFound) Error() string {
	return fmt.Sprintf("[GET /gov/proposals/{proposalId}/votes/{voter}][%d] getGovProposalsProposalIdVotesVoterNotFound ", 404)
}

func (o *GetGovProposalsProposalIDVotesVoterNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetGovProposalsProposalIDVotesVoterInternalServerError creates a GetGovProposalsProposalIDVotesVoterInternalServerError with default headers values
func NewGetGovProposalsProposalIDVotesVoterInternalServerError() *GetGovProposalsProposalIDVotesVoterInternalServerError {
	return &GetGovProposalsProposalIDVotesVoterInternalServerError{}
}

/*GetGovProposalsProposalIDVotesVoterInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetGovProposalsProposalIDVotesVoterInternalServerError struct {
}

func (o *GetGovProposalsProposalIDVotesVoterInternalServerError) Error() string {
	return fmt.Sprintf("[GET /gov/proposals/{proposalId}/votes/{voter}][%d] getGovProposalsProposalIdVotesVoterInternalServerError ", 500)
}

func (o *GetGovProposalsProposalIDVotesVoterInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
