// Code generated by go-swagger; DO NOT EDIT.

package governance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGovProposalsProposalIDDepositsDepositorParams creates a new GetGovProposalsProposalIDDepositsDepositorParams object
// with the default values initialized.
func NewGetGovProposalsProposalIDDepositsDepositorParams() *GetGovProposalsProposalIDDepositsDepositorParams {
	var ()
	return &GetGovProposalsProposalIDDepositsDepositorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetGovProposalsProposalIDDepositsDepositorParamsWithTimeout creates a new GetGovProposalsProposalIDDepositsDepositorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetGovProposalsProposalIDDepositsDepositorParamsWithTimeout(timeout time.Duration) *GetGovProposalsProposalIDDepositsDepositorParams {
	var ()
	return &GetGovProposalsProposalIDDepositsDepositorParams{

		timeout: timeout,
	}
}

// NewGetGovProposalsProposalIDDepositsDepositorParamsWithContext creates a new GetGovProposalsProposalIDDepositsDepositorParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetGovProposalsProposalIDDepositsDepositorParamsWithContext(ctx context.Context) *GetGovProposalsProposalIDDepositsDepositorParams {
	var ()
	return &GetGovProposalsProposalIDDepositsDepositorParams{

		Context: ctx,
	}
}

// NewGetGovProposalsProposalIDDepositsDepositorParamsWithHTTPClient creates a new GetGovProposalsProposalIDDepositsDepositorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetGovProposalsProposalIDDepositsDepositorParamsWithHTTPClient(client *http.Client) *GetGovProposalsProposalIDDepositsDepositorParams {
	var ()
	return &GetGovProposalsProposalIDDepositsDepositorParams{
		HTTPClient: client,
	}
}

/*GetGovProposalsProposalIDDepositsDepositorParams contains all the parameters to send to the API endpoint
for the get gov proposals proposal ID deposits depositor operation typically these are written to a http.Request
*/
type GetGovProposalsProposalIDDepositsDepositorParams struct {

	/*Depositor
	  Bech32 depositor address

	*/
	Depositor string
	/*ProposalID
	  proposal id

	*/
	ProposalID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get gov proposals proposal ID deposits depositor params
func (o *GetGovProposalsProposalIDDepositsDepositorParams) WithTimeout(timeout time.Duration) *GetGovProposalsProposalIDDepositsDepositorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get gov proposals proposal ID deposits depositor params
func (o *GetGovProposalsProposalIDDepositsDepositorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get gov proposals proposal ID deposits depositor params
func (o *GetGovProposalsProposalIDDepositsDepositorParams) WithContext(ctx context.Context) *GetGovProposalsProposalIDDepositsDepositorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get gov proposals proposal ID deposits depositor params
func (o *GetGovProposalsProposalIDDepositsDepositorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get gov proposals proposal ID deposits depositor params
func (o *GetGovProposalsProposalIDDepositsDepositorParams) WithHTTPClient(client *http.Client) *GetGovProposalsProposalIDDepositsDepositorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get gov proposals proposal ID deposits depositor params
func (o *GetGovProposalsProposalIDDepositsDepositorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDepositor adds the depositor to the get gov proposals proposal ID deposits depositor params
func (o *GetGovProposalsProposalIDDepositsDepositorParams) WithDepositor(depositor string) *GetGovProposalsProposalIDDepositsDepositorParams {
	o.SetDepositor(depositor)
	return o
}

// SetDepositor adds the depositor to the get gov proposals proposal ID deposits depositor params
func (o *GetGovProposalsProposalIDDepositsDepositorParams) SetDepositor(depositor string) {
	o.Depositor = depositor
}

// WithProposalID adds the proposalID to the get gov proposals proposal ID deposits depositor params
func (o *GetGovProposalsProposalIDDepositsDepositorParams) WithProposalID(proposalID string) *GetGovProposalsProposalIDDepositsDepositorParams {
	o.SetProposalID(proposalID)
	return o
}

// SetProposalID adds the proposalId to the get gov proposals proposal ID deposits depositor params
func (o *GetGovProposalsProposalIDDepositsDepositorParams) SetProposalID(proposalID string) {
	o.ProposalID = proposalID
}

// WriteToRequest writes these params to a swagger request
func (o *GetGovProposalsProposalIDDepositsDepositorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param depositor
	if err := r.SetPathParam("depositor", o.Depositor); err != nil {
		return err
	}

	// path param proposalId
	if err := r.SetPathParam("proposalId", o.ProposalID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
