// Code generated by go-swagger; DO NOT EDIT.

package governance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetGovParametersVotingReader is a Reader for the GetGovParametersVoting structure.
type GetGovParametersVotingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGovParametersVotingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGovParametersVotingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetGovParametersVotingBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetGovParametersVotingNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetGovParametersVotingInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetGovParametersVotingOK creates a GetGovParametersVotingOK with default headers values
func NewGetGovParametersVotingOK() *GetGovParametersVotingOK {
	return &GetGovParametersVotingOK{}
}

/*GetGovParametersVotingOK handles this case with default header values.

OK
*/
type GetGovParametersVotingOK struct {
	Payload *GetGovParametersVotingOKBody
}

func (o *GetGovParametersVotingOK) Error() string {
	return fmt.Sprintf("[GET /gov/parameters/voting][%d] getGovParametersVotingOK  %+v", 200, o.Payload)
}

func (o *GetGovParametersVotingOK) GetPayload() *GetGovParametersVotingOKBody {
	return o.Payload
}

func (o *GetGovParametersVotingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetGovParametersVotingOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGovParametersVotingBadRequest creates a GetGovParametersVotingBadRequest with default headers values
func NewGetGovParametersVotingBadRequest() *GetGovParametersVotingBadRequest {
	return &GetGovParametersVotingBadRequest{}
}

/*GetGovParametersVotingBadRequest handles this case with default header values.

<other_path> is not a valid query request path
*/
type GetGovParametersVotingBadRequest struct {
}

func (o *GetGovParametersVotingBadRequest) Error() string {
	return fmt.Sprintf("[GET /gov/parameters/voting][%d] getGovParametersVotingBadRequest ", 400)
}

func (o *GetGovParametersVotingBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetGovParametersVotingNotFound creates a GetGovParametersVotingNotFound with default headers values
func NewGetGovParametersVotingNotFound() *GetGovParametersVotingNotFound {
	return &GetGovParametersVotingNotFound{}
}

/*GetGovParametersVotingNotFound handles this case with default header values.

Found no voting parameters
*/
type GetGovParametersVotingNotFound struct {
}

func (o *GetGovParametersVotingNotFound) Error() string {
	return fmt.Sprintf("[GET /gov/parameters/voting][%d] getGovParametersVotingNotFound ", 404)
}

func (o *GetGovParametersVotingNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetGovParametersVotingInternalServerError creates a GetGovParametersVotingInternalServerError with default headers values
func NewGetGovParametersVotingInternalServerError() *GetGovParametersVotingInternalServerError {
	return &GetGovParametersVotingInternalServerError{}
}

/*GetGovParametersVotingInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetGovParametersVotingInternalServerError struct {
}

func (o *GetGovParametersVotingInternalServerError) Error() string {
	return fmt.Sprintf("[GET /gov/parameters/voting][%d] getGovParametersVotingInternalServerError ", 500)
}

func (o *GetGovParametersVotingInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetGovParametersVotingOKBody get gov parameters voting o k body
swagger:model GetGovParametersVotingOKBody
*/
type GetGovParametersVotingOKBody struct {

	// height
	Height string `json:"height,omitempty"`

	// result
	Result *GetGovParametersVotingOKBodyResult `json:"result,omitempty"`
}

// Validate validates this get gov parameters voting o k body
func (o *GetGovParametersVotingOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetGovParametersVotingOKBody) validateResult(formats strfmt.Registry) error {

	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getGovParametersVotingOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetGovParametersVotingOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetGovParametersVotingOKBody) UnmarshalBinary(b []byte) error {
	var res GetGovParametersVotingOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetGovParametersVotingOKBodyResult get gov parameters voting o k body result
swagger:model GetGovParametersVotingOKBodyResult
*/
type GetGovParametersVotingOKBodyResult struct {

	// voting period
	VotingPeriod string `json:"voting_period,omitempty"`
}

// Validate validates this get gov parameters voting o k body result
func (o *GetGovParametersVotingOKBodyResult) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetGovParametersVotingOKBodyResult) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetGovParametersVotingOKBodyResult) UnmarshalBinary(b []byte) error {
	var res GetGovParametersVotingOKBodyResult
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
