// Code generated by go-swagger; DO NOT EDIT.

package governance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/terra-project/mantle/lcd/models"
)

// GetGovProposalsProposalIDDepositsReader is a Reader for the GetGovProposalsProposalIDDeposits structure.
type GetGovProposalsProposalIDDepositsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGovProposalsProposalIDDepositsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGovProposalsProposalIDDepositsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetGovProposalsProposalIDDepositsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetGovProposalsProposalIDDepositsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetGovProposalsProposalIDDepositsOK creates a GetGovProposalsProposalIDDepositsOK with default headers values
func NewGetGovProposalsProposalIDDepositsOK() *GetGovProposalsProposalIDDepositsOK {
	return &GetGovProposalsProposalIDDepositsOK{}
}

/*GetGovProposalsProposalIDDepositsOK handles this case with default header values.

OK
*/
type GetGovProposalsProposalIDDepositsOK struct {
	Payload []*models.Deposit
}

func (o *GetGovProposalsProposalIDDepositsOK) Error() string {
	return fmt.Sprintf("[GET /gov/proposals/{proposalId}/deposits][%d] getGovProposalsProposalIdDepositsOK  %+v", 200, o.Payload)
}

func (o *GetGovProposalsProposalIDDepositsOK) GetPayload() []*models.Deposit {
	return o.Payload
}

func (o *GetGovProposalsProposalIDDepositsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGovProposalsProposalIDDepositsBadRequest creates a GetGovProposalsProposalIDDepositsBadRequest with default headers values
func NewGetGovProposalsProposalIDDepositsBadRequest() *GetGovProposalsProposalIDDepositsBadRequest {
	return &GetGovProposalsProposalIDDepositsBadRequest{}
}

/*GetGovProposalsProposalIDDepositsBadRequest handles this case with default header values.

Invalid proposal id
*/
type GetGovProposalsProposalIDDepositsBadRequest struct {
}

func (o *GetGovProposalsProposalIDDepositsBadRequest) Error() string {
	return fmt.Sprintf("[GET /gov/proposals/{proposalId}/deposits][%d] getGovProposalsProposalIdDepositsBadRequest ", 400)
}

func (o *GetGovProposalsProposalIDDepositsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetGovProposalsProposalIDDepositsInternalServerError creates a GetGovProposalsProposalIDDepositsInternalServerError with default headers values
func NewGetGovProposalsProposalIDDepositsInternalServerError() *GetGovProposalsProposalIDDepositsInternalServerError {
	return &GetGovProposalsProposalIDDepositsInternalServerError{}
}

/*GetGovProposalsProposalIDDepositsInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetGovProposalsProposalIDDepositsInternalServerError struct {
}

func (o *GetGovProposalsProposalIDDepositsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /gov/proposals/{proposalId}/deposits][%d] getGovProposalsProposalIdDepositsInternalServerError ", 500)
}

func (o *GetGovProposalsProposalIDDepositsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
