// Code generated by go-swagger; DO NOT EDIT.

package governance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGovProposalsProposalIDParams creates a new GetGovProposalsProposalIDParams object
// with the default values initialized.
func NewGetGovProposalsProposalIDParams() *GetGovProposalsProposalIDParams {
	var ()
	return &GetGovProposalsProposalIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetGovProposalsProposalIDParamsWithTimeout creates a new GetGovProposalsProposalIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetGovProposalsProposalIDParamsWithTimeout(timeout time.Duration) *GetGovProposalsProposalIDParams {
	var ()
	return &GetGovProposalsProposalIDParams{

		timeout: timeout,
	}
}

// NewGetGovProposalsProposalIDParamsWithContext creates a new GetGovProposalsProposalIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetGovProposalsProposalIDParamsWithContext(ctx context.Context) *GetGovProposalsProposalIDParams {
	var ()
	return &GetGovProposalsProposalIDParams{

		Context: ctx,
	}
}

// NewGetGovProposalsProposalIDParamsWithHTTPClient creates a new GetGovProposalsProposalIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetGovProposalsProposalIDParamsWithHTTPClient(client *http.Client) *GetGovProposalsProposalIDParams {
	var ()
	return &GetGovProposalsProposalIDParams{
		HTTPClient: client,
	}
}

/*GetGovProposalsProposalIDParams contains all the parameters to send to the API endpoint
for the get gov proposals proposal ID operation typically these are written to a http.Request
*/
type GetGovProposalsProposalIDParams struct {

	/*ProposalID*/
	ProposalID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get gov proposals proposal ID params
func (o *GetGovProposalsProposalIDParams) WithTimeout(timeout time.Duration) *GetGovProposalsProposalIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get gov proposals proposal ID params
func (o *GetGovProposalsProposalIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get gov proposals proposal ID params
func (o *GetGovProposalsProposalIDParams) WithContext(ctx context.Context) *GetGovProposalsProposalIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get gov proposals proposal ID params
func (o *GetGovProposalsProposalIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get gov proposals proposal ID params
func (o *GetGovProposalsProposalIDParams) WithHTTPClient(client *http.Client) *GetGovProposalsProposalIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get gov proposals proposal ID params
func (o *GetGovProposalsProposalIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProposalID adds the proposalID to the get gov proposals proposal ID params
func (o *GetGovProposalsProposalIDParams) WithProposalID(proposalID string) *GetGovProposalsProposalIDParams {
	o.SetProposalID(proposalID)
	return o
}

// SetProposalID adds the proposalId to the get gov proposals proposal ID params
func (o *GetGovProposalsProposalIDParams) SetProposalID(proposalID string) {
	o.ProposalID = proposalID
}

// WriteToRequest writes these params to a swagger request
func (o *GetGovProposalsProposalIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param proposalId
	if err := r.SetPathParam("proposalId", o.ProposalID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
