// Code generated by go-swagger; DO NOT EDIT.

package governance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/terra-project/mantle-sdk/lcd/models"
)

// PostGovProposalsTaxRateUpdateReader is a Reader for the PostGovProposalsTaxRateUpdate structure.
type PostGovProposalsTaxRateUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostGovProposalsTaxRateUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostGovProposalsTaxRateUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostGovProposalsTaxRateUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostGovProposalsTaxRateUpdateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostGovProposalsTaxRateUpdateOK creates a PostGovProposalsTaxRateUpdateOK with default headers values
func NewPostGovProposalsTaxRateUpdateOK() *PostGovProposalsTaxRateUpdateOK {
	return &PostGovProposalsTaxRateUpdateOK{}
}

/*PostGovProposalsTaxRateUpdateOK handles this case with default header values.

The transaction was successfully generated
*/
type PostGovProposalsTaxRateUpdateOK struct {
	Payload *models.StdTx
}

func (o *PostGovProposalsTaxRateUpdateOK) Error() string {
	return fmt.Sprintf("[POST /gov/proposals/tax_rate_update][%d] postGovProposalsTaxRateUpdateOK  %+v", 200, o.Payload)
}

func (o *PostGovProposalsTaxRateUpdateOK) GetPayload() *models.StdTx {
	return o.Payload
}

func (o *PostGovProposalsTaxRateUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StdTx)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostGovProposalsTaxRateUpdateBadRequest creates a PostGovProposalsTaxRateUpdateBadRequest with default headers values
func NewPostGovProposalsTaxRateUpdateBadRequest() *PostGovProposalsTaxRateUpdateBadRequest {
	return &PostGovProposalsTaxRateUpdateBadRequest{}
}

/*PostGovProposalsTaxRateUpdateBadRequest handles this case with default header values.

Invalid proposal body
*/
type PostGovProposalsTaxRateUpdateBadRequest struct {
}

func (o *PostGovProposalsTaxRateUpdateBadRequest) Error() string {
	return fmt.Sprintf("[POST /gov/proposals/tax_rate_update][%d] postGovProposalsTaxRateUpdateBadRequest ", 400)
}

func (o *PostGovProposalsTaxRateUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostGovProposalsTaxRateUpdateInternalServerError creates a PostGovProposalsTaxRateUpdateInternalServerError with default headers values
func NewPostGovProposalsTaxRateUpdateInternalServerError() *PostGovProposalsTaxRateUpdateInternalServerError {
	return &PostGovProposalsTaxRateUpdateInternalServerError{}
}

/*PostGovProposalsTaxRateUpdateInternalServerError handles this case with default header values.

Internal Server Error
*/
type PostGovProposalsTaxRateUpdateInternalServerError struct {
}

func (o *PostGovProposalsTaxRateUpdateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /gov/proposals/tax_rate_update][%d] postGovProposalsTaxRateUpdateInternalServerError ", 500)
}

func (o *PostGovProposalsTaxRateUpdateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*PostGovProposalsTaxRateUpdateBody post gov proposals tax rate update body
swagger:model PostGovProposalsTaxRateUpdateBody
*/
type PostGovProposalsTaxRateUpdateBody struct {

	// base req
	BaseReq *models.BaseReq `json:"base_req,omitempty"`

	// deposit
	Deposit []*models.Coin `json:"deposit"`

	// description
	Description string `json:"description,omitempty"`

	// proposer
	Proposer models.Address `json:"proposer,omitempty"`

	// tax rate
	TaxRate float32 `json:"tax_rate,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this post gov proposals tax rate update body
func (o *PostGovProposalsTaxRateUpdateBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBaseReq(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDeposit(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateProposer(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostGovProposalsTaxRateUpdateBody) validateBaseReq(formats strfmt.Registry) error {

	if swag.IsZero(o.BaseReq) { // not required
		return nil
	}

	if o.BaseReq != nil {
		if err := o.BaseReq.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("post_proposal_body" + "." + "base_req")
			}
			return err
		}
	}

	return nil
}

func (o *PostGovProposalsTaxRateUpdateBody) validateDeposit(formats strfmt.Registry) error {

	if swag.IsZero(o.Deposit) { // not required
		return nil
	}

	for i := 0; i < len(o.Deposit); i++ {
		if swag.IsZero(o.Deposit[i]) { // not required
			continue
		}

		if o.Deposit[i] != nil {
			if err := o.Deposit[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("post_proposal_body" + "." + "deposit" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *PostGovProposalsTaxRateUpdateBody) validateProposer(formats strfmt.Registry) error {

	if swag.IsZero(o.Proposer) { // not required
		return nil
	}

	if err := o.Proposer.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("post_proposal_body" + "." + "proposer")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostGovProposalsTaxRateUpdateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostGovProposalsTaxRateUpdateBody) UnmarshalBinary(b []byte) error {
	var res PostGovProposalsTaxRateUpdateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
