// Code generated by go-swagger; DO NOT EDIT.

package distribution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDistributionValidatorsValidatorAddrRewardsParams creates a new GetDistributionValidatorsValidatorAddrRewardsParams object
// with the default values initialized.
func NewGetDistributionValidatorsValidatorAddrRewardsParams() *GetDistributionValidatorsValidatorAddrRewardsParams {
	var ()
	return &GetDistributionValidatorsValidatorAddrRewardsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDistributionValidatorsValidatorAddrRewardsParamsWithTimeout creates a new GetDistributionValidatorsValidatorAddrRewardsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDistributionValidatorsValidatorAddrRewardsParamsWithTimeout(timeout time.Duration) *GetDistributionValidatorsValidatorAddrRewardsParams {
	var ()
	return &GetDistributionValidatorsValidatorAddrRewardsParams{

		timeout: timeout,
	}
}

// NewGetDistributionValidatorsValidatorAddrRewardsParamsWithContext creates a new GetDistributionValidatorsValidatorAddrRewardsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDistributionValidatorsValidatorAddrRewardsParamsWithContext(ctx context.Context) *GetDistributionValidatorsValidatorAddrRewardsParams {
	var ()
	return &GetDistributionValidatorsValidatorAddrRewardsParams{

		Context: ctx,
	}
}

// NewGetDistributionValidatorsValidatorAddrRewardsParamsWithHTTPClient creates a new GetDistributionValidatorsValidatorAddrRewardsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDistributionValidatorsValidatorAddrRewardsParamsWithHTTPClient(client *http.Client) *GetDistributionValidatorsValidatorAddrRewardsParams {
	var ()
	return &GetDistributionValidatorsValidatorAddrRewardsParams{
		HTTPClient: client,
	}
}

/*GetDistributionValidatorsValidatorAddrRewardsParams contains all the parameters to send to the API endpoint
for the get distribution validators validator addr rewards operation typically these are written to a http.Request
*/
type GetDistributionValidatorsValidatorAddrRewardsParams struct {

	/*ValidatorAddr
	  Bech32 OperatorAddress of validator

	*/
	ValidatorAddr string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get distribution validators validator addr rewards params
func (o *GetDistributionValidatorsValidatorAddrRewardsParams) WithTimeout(timeout time.Duration) *GetDistributionValidatorsValidatorAddrRewardsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get distribution validators validator addr rewards params
func (o *GetDistributionValidatorsValidatorAddrRewardsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get distribution validators validator addr rewards params
func (o *GetDistributionValidatorsValidatorAddrRewardsParams) WithContext(ctx context.Context) *GetDistributionValidatorsValidatorAddrRewardsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get distribution validators validator addr rewards params
func (o *GetDistributionValidatorsValidatorAddrRewardsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get distribution validators validator addr rewards params
func (o *GetDistributionValidatorsValidatorAddrRewardsParams) WithHTTPClient(client *http.Client) *GetDistributionValidatorsValidatorAddrRewardsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get distribution validators validator addr rewards params
func (o *GetDistributionValidatorsValidatorAddrRewardsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithValidatorAddr adds the validatorAddr to the get distribution validators validator addr rewards params
func (o *GetDistributionValidatorsValidatorAddrRewardsParams) WithValidatorAddr(validatorAddr string) *GetDistributionValidatorsValidatorAddrRewardsParams {
	o.SetValidatorAddr(validatorAddr)
	return o
}

// SetValidatorAddr adds the validatorAddr to the get distribution validators validator addr rewards params
func (o *GetDistributionValidatorsValidatorAddrRewardsParams) SetValidatorAddr(validatorAddr string) {
	o.ValidatorAddr = validatorAddr
}

// WriteToRequest writes these params to a swagger request
func (o *GetDistributionValidatorsValidatorAddrRewardsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param validatorAddr
	if err := r.SetPathParam("validatorAddr", o.ValidatorAddr); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
