// Code generated by go-swagger; DO NOT EDIT.

package distribution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams creates a new GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams object
// with the default values initialized.
func NewGetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams() *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams {
	var ()
	return &GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParamsWithTimeout creates a new GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParamsWithTimeout(timeout time.Duration) *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams {
	var ()
	return &GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams{

		timeout: timeout,
	}
}

// NewGetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParamsWithContext creates a new GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParamsWithContext(ctx context.Context) *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams {
	var ()
	return &GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams{

		Context: ctx,
	}
}

// NewGetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParamsWithHTTPClient creates a new GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParamsWithHTTPClient(client *http.Client) *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams {
	var ()
	return &GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams{
		HTTPClient: client,
	}
}

/*GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams contains all the parameters to send to the API endpoint
for the get distribution delegators delegator addr rewards validator addr operation typically these are written to a http.Request
*/
type GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams struct {

	/*DelegatorAddr
	  Bech32 AccAddress of Delegator

	*/
	DelegatorAddr string
	/*ValidatorAddr
	  Bech32 OperatorAddress of validator

	*/
	ValidatorAddr string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get distribution delegators delegator addr rewards validator addr params
func (o *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams) WithTimeout(timeout time.Duration) *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get distribution delegators delegator addr rewards validator addr params
func (o *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get distribution delegators delegator addr rewards validator addr params
func (o *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams) WithContext(ctx context.Context) *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get distribution delegators delegator addr rewards validator addr params
func (o *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get distribution delegators delegator addr rewards validator addr params
func (o *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams) WithHTTPClient(client *http.Client) *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get distribution delegators delegator addr rewards validator addr params
func (o *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDelegatorAddr adds the delegatorAddr to the get distribution delegators delegator addr rewards validator addr params
func (o *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams) WithDelegatorAddr(delegatorAddr string) *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams {
	o.SetDelegatorAddr(delegatorAddr)
	return o
}

// SetDelegatorAddr adds the delegatorAddr to the get distribution delegators delegator addr rewards validator addr params
func (o *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams) SetDelegatorAddr(delegatorAddr string) {
	o.DelegatorAddr = delegatorAddr
}

// WithValidatorAddr adds the validatorAddr to the get distribution delegators delegator addr rewards validator addr params
func (o *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams) WithValidatorAddr(validatorAddr string) *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams {
	o.SetValidatorAddr(validatorAddr)
	return o
}

// SetValidatorAddr adds the validatorAddr to the get distribution delegators delegator addr rewards validator addr params
func (o *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams) SetValidatorAddr(validatorAddr string) {
	o.ValidatorAddr = validatorAddr
}

// WriteToRequest writes these params to a swagger request
func (o *GetDistributionDelegatorsDelegatorAddrRewardsValidatorAddrParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param delegatorAddr
	if err := r.SetPathParam("delegatorAddr", o.DelegatorAddr); err != nil {
		return err
	}

	// path param validatorAddr
	if err := r.SetPathParam("validatorAddr", o.ValidatorAddr); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
