// Code generated by go-swagger; DO NOT EDIT.

package distribution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/terra-project/mantle-sdk/lcd/models"
)

// GetDistributionDelegatorsDelegatorAddrWithdrawAddressReader is a Reader for the GetDistributionDelegatorsDelegatorAddrWithdrawAddress structure.
type GetDistributionDelegatorsDelegatorAddrWithdrawAddressReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDistributionDelegatorsDelegatorAddrWithdrawAddressReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDistributionDelegatorsDelegatorAddrWithdrawAddressOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetDistributionDelegatorsDelegatorAddrWithdrawAddressBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetDistributionDelegatorsDelegatorAddrWithdrawAddressInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDistributionDelegatorsDelegatorAddrWithdrawAddressOK creates a GetDistributionDelegatorsDelegatorAddrWithdrawAddressOK with default headers values
func NewGetDistributionDelegatorsDelegatorAddrWithdrawAddressOK() *GetDistributionDelegatorsDelegatorAddrWithdrawAddressOK {
	return &GetDistributionDelegatorsDelegatorAddrWithdrawAddressOK{}
}

/*GetDistributionDelegatorsDelegatorAddrWithdrawAddressOK handles this case with default header values.

OK
*/
type GetDistributionDelegatorsDelegatorAddrWithdrawAddressOK struct {
	Payload *GetDistributionDelegatorsDelegatorAddrWithdrawAddressOKBody
}

func (o *GetDistributionDelegatorsDelegatorAddrWithdrawAddressOK) Error() string {
	return fmt.Sprintf("[GET /distribution/delegators/{delegatorAddr}/withdraw_address][%d] getDistributionDelegatorsDelegatorAddrWithdrawAddressOK  %+v", 200, o.Payload)
}

func (o *GetDistributionDelegatorsDelegatorAddrWithdrawAddressOK) GetPayload() *GetDistributionDelegatorsDelegatorAddrWithdrawAddressOKBody {
	return o.Payload
}

func (o *GetDistributionDelegatorsDelegatorAddrWithdrawAddressOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetDistributionDelegatorsDelegatorAddrWithdrawAddressOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDistributionDelegatorsDelegatorAddrWithdrawAddressBadRequest creates a GetDistributionDelegatorsDelegatorAddrWithdrawAddressBadRequest with default headers values
func NewGetDistributionDelegatorsDelegatorAddrWithdrawAddressBadRequest() *GetDistributionDelegatorsDelegatorAddrWithdrawAddressBadRequest {
	return &GetDistributionDelegatorsDelegatorAddrWithdrawAddressBadRequest{}
}

/*GetDistributionDelegatorsDelegatorAddrWithdrawAddressBadRequest handles this case with default header values.

Invalid delegator address
*/
type GetDistributionDelegatorsDelegatorAddrWithdrawAddressBadRequest struct {
}

func (o *GetDistributionDelegatorsDelegatorAddrWithdrawAddressBadRequest) Error() string {
	return fmt.Sprintf("[GET /distribution/delegators/{delegatorAddr}/withdraw_address][%d] getDistributionDelegatorsDelegatorAddrWithdrawAddressBadRequest ", 400)
}

func (o *GetDistributionDelegatorsDelegatorAddrWithdrawAddressBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDistributionDelegatorsDelegatorAddrWithdrawAddressInternalServerError creates a GetDistributionDelegatorsDelegatorAddrWithdrawAddressInternalServerError with default headers values
func NewGetDistributionDelegatorsDelegatorAddrWithdrawAddressInternalServerError() *GetDistributionDelegatorsDelegatorAddrWithdrawAddressInternalServerError {
	return &GetDistributionDelegatorsDelegatorAddrWithdrawAddressInternalServerError{}
}

/*GetDistributionDelegatorsDelegatorAddrWithdrawAddressInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetDistributionDelegatorsDelegatorAddrWithdrawAddressInternalServerError struct {
}

func (o *GetDistributionDelegatorsDelegatorAddrWithdrawAddressInternalServerError) Error() string {
	return fmt.Sprintf("[GET /distribution/delegators/{delegatorAddr}/withdraw_address][%d] getDistributionDelegatorsDelegatorAddrWithdrawAddressInternalServerError ", 500)
}

func (o *GetDistributionDelegatorsDelegatorAddrWithdrawAddressInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetDistributionDelegatorsDelegatorAddrWithdrawAddressOKBody get distribution delegators delegator addr withdraw address o k body
swagger:model GetDistributionDelegatorsDelegatorAddrWithdrawAddressOKBody
*/
type GetDistributionDelegatorsDelegatorAddrWithdrawAddressOKBody struct {

	// height
	Height string `json:"height,omitempty"`

	// result
	Result models.Address `json:"result,omitempty"`
}

// Validate validates this get distribution delegators delegator addr withdraw address o k body
func (o *GetDistributionDelegatorsDelegatorAddrWithdrawAddressOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetDistributionDelegatorsDelegatorAddrWithdrawAddressOKBody) validateResult(formats strfmt.Registry) error {

	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if err := o.Result.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("getDistributionDelegatorsDelegatorAddrWithdrawAddressOK" + "." + "result")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetDistributionDelegatorsDelegatorAddrWithdrawAddressOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetDistributionDelegatorsDelegatorAddrWithdrawAddressOKBody) UnmarshalBinary(b []byte) error {
	var res GetDistributionDelegatorsDelegatorAddrWithdrawAddressOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
