// Code generated by go-swagger; DO NOT EDIT.

package distribution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostDistributionValidatorsValidatorAddrRewardsParams creates a new PostDistributionValidatorsValidatorAddrRewardsParams object
// with the default values initialized.
func NewPostDistributionValidatorsValidatorAddrRewardsParams() *PostDistributionValidatorsValidatorAddrRewardsParams {
	var ()
	return &PostDistributionValidatorsValidatorAddrRewardsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostDistributionValidatorsValidatorAddrRewardsParamsWithTimeout creates a new PostDistributionValidatorsValidatorAddrRewardsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostDistributionValidatorsValidatorAddrRewardsParamsWithTimeout(timeout time.Duration) *PostDistributionValidatorsValidatorAddrRewardsParams {
	var ()
	return &PostDistributionValidatorsValidatorAddrRewardsParams{

		timeout: timeout,
	}
}

// NewPostDistributionValidatorsValidatorAddrRewardsParamsWithContext creates a new PostDistributionValidatorsValidatorAddrRewardsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostDistributionValidatorsValidatorAddrRewardsParamsWithContext(ctx context.Context) *PostDistributionValidatorsValidatorAddrRewardsParams {
	var ()
	return &PostDistributionValidatorsValidatorAddrRewardsParams{

		Context: ctx,
	}
}

// NewPostDistributionValidatorsValidatorAddrRewardsParamsWithHTTPClient creates a new PostDistributionValidatorsValidatorAddrRewardsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostDistributionValidatorsValidatorAddrRewardsParamsWithHTTPClient(client *http.Client) *PostDistributionValidatorsValidatorAddrRewardsParams {
	var ()
	return &PostDistributionValidatorsValidatorAddrRewardsParams{
		HTTPClient: client,
	}
}

/*PostDistributionValidatorsValidatorAddrRewardsParams contains all the parameters to send to the API endpoint
for the post distribution validators validator addr rewards operation typically these are written to a http.Request
*/
type PostDistributionValidatorsValidatorAddrRewardsParams struct {

	/*WithdrawRequestBody*/
	WithdrawRequestBody PostDistributionValidatorsValidatorAddrRewardsBody
	/*ValidatorAddr
	  Bech32 OperatorAddress of validator

	*/
	ValidatorAddr string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post distribution validators validator addr rewards params
func (o *PostDistributionValidatorsValidatorAddrRewardsParams) WithTimeout(timeout time.Duration) *PostDistributionValidatorsValidatorAddrRewardsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post distribution validators validator addr rewards params
func (o *PostDistributionValidatorsValidatorAddrRewardsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post distribution validators validator addr rewards params
func (o *PostDistributionValidatorsValidatorAddrRewardsParams) WithContext(ctx context.Context) *PostDistributionValidatorsValidatorAddrRewardsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post distribution validators validator addr rewards params
func (o *PostDistributionValidatorsValidatorAddrRewardsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post distribution validators validator addr rewards params
func (o *PostDistributionValidatorsValidatorAddrRewardsParams) WithHTTPClient(client *http.Client) *PostDistributionValidatorsValidatorAddrRewardsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post distribution validators validator addr rewards params
func (o *PostDistributionValidatorsValidatorAddrRewardsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWithdrawRequestBody adds the withdrawRequestBody to the post distribution validators validator addr rewards params
func (o *PostDistributionValidatorsValidatorAddrRewardsParams) WithWithdrawRequestBody(withdrawRequestBody PostDistributionValidatorsValidatorAddrRewardsBody) *PostDistributionValidatorsValidatorAddrRewardsParams {
	o.SetWithdrawRequestBody(withdrawRequestBody)
	return o
}

// SetWithdrawRequestBody adds the withdrawRequestBody to the post distribution validators validator addr rewards params
func (o *PostDistributionValidatorsValidatorAddrRewardsParams) SetWithdrawRequestBody(withdrawRequestBody PostDistributionValidatorsValidatorAddrRewardsBody) {
	o.WithdrawRequestBody = withdrawRequestBody
}

// WithValidatorAddr adds the validatorAddr to the post distribution validators validator addr rewards params
func (o *PostDistributionValidatorsValidatorAddrRewardsParams) WithValidatorAddr(validatorAddr string) *PostDistributionValidatorsValidatorAddrRewardsParams {
	o.SetValidatorAddr(validatorAddr)
	return o
}

// SetValidatorAddr adds the validatorAddr to the post distribution validators validator addr rewards params
func (o *PostDistributionValidatorsValidatorAddrRewardsParams) SetValidatorAddr(validatorAddr string) {
	o.ValidatorAddr = validatorAddr
}

// WriteToRequest writes these params to a swagger request
func (o *PostDistributionValidatorsValidatorAddrRewardsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.WithdrawRequestBody); err != nil {
		return err
	}

	// path param validatorAddr
	if err := r.SetPathParam("validatorAddr", o.ValidatorAddr); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
