// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AggregatePrevoteReq aggregate prevote req
//
// swagger:model AggregatePrevoteReq
type AggregatePrevoteReq struct {

	// base req
	BaseReq *BaseReq `json:"base_req,omitempty"`

	// exchange rates of Luna in denom currencies are to make aggregate prevote hash; this field is required to submit prevote in case absence of hash
	ExchangeRates string `json:"exchange_rates,omitempty"`

	// hex string; hash of next vote; empty == skip prevote
	Hash string `json:"hash,omitempty"`

	// salt is to make prevote hash; this field is required to submit prevote in case  absence of hash
	Salt string `json:"salt,omitempty"`
}

// Validate validates this aggregate prevote req
func (m *AggregatePrevoteReq) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBaseReq(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AggregatePrevoteReq) validateBaseReq(formats strfmt.Registry) error {

	if swag.IsZero(m.BaseReq) { // not required
		return nil
	}

	if m.BaseReq != nil {
		if err := m.BaseReq.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("base_req")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AggregatePrevoteReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AggregatePrevoteReq) UnmarshalBinary(b []byte) error {
	var res AggregatePrevoteReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
