// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BaseLazyGradedVestingAccount base lazy graded vesting account
//
// swagger:model BaseLazyGradedVestingAccount
type BaseLazyGradedVestingAccount struct {

	// base vesting account
	BaseVestingAccount *BaseVestingAccount `json:"BaseVestingAccount,omitempty"`

	// vesting schedules
	VestingSchedules []*VestingSchedule `json:"vesting_schedules"`
}

// Validate validates this base lazy graded vesting account
func (m *BaseLazyGradedVestingAccount) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBaseVestingAccount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVestingSchedules(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BaseLazyGradedVestingAccount) validateBaseVestingAccount(formats strfmt.Registry) error {

	if swag.IsZero(m.BaseVestingAccount) { // not required
		return nil
	}

	if m.BaseVestingAccount != nil {
		if err := m.BaseVestingAccount.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("BaseVestingAccount")
			}
			return err
		}
	}

	return nil
}

func (m *BaseLazyGradedVestingAccount) validateVestingSchedules(formats strfmt.Registry) error {

	if swag.IsZero(m.VestingSchedules) { // not required
		return nil
	}

	for i := 0; i < len(m.VestingSchedules); i++ {
		if swag.IsZero(m.VestingSchedules[i]) { // not required
			continue
		}

		if m.VestingSchedules[i] != nil {
			if err := m.VestingSchedules[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("vesting_schedules" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *BaseLazyGradedVestingAccount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BaseLazyGradedVestingAccount) UnmarshalBinary(b []byte) error {
	var res BaseLazyGradedVestingAccount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
