// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MarketParams market params
//
// swagger:model MarketParams
type MarketParams struct {

	// daily luna delta limit
	DailyLunaDeltaLimit float64 `json:"daily_luna_delta_limit,omitempty"`

	// max swap spread
	MaxSwapSpread float64 `json:"max_swap_spread,omitempty"`

	// min swap spread
	MinSwapSpread float64 `json:"min_swap_spread,omitempty"`
}

// Validate validates this market params
func (m *MarketParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MarketParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MarketParams) UnmarshalBinary(b []byte) error {
	var res MarketParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
