// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OracleParams oracle params
//
// swagger:model OracleParams
type OracleParams struct {

	// drop threshold
	DropThreshold float64 `json:"drop_threshold,omitempty"`

	// oracle reward band
	OracleRewardBand float64 `json:"oracle_reward_band,omitempty"`

	// vote period
	VotePeriod float64 `json:"vote_period,omitempty"`

	// vote threshold
	VoteThreshold float64 `json:"vote_threshold,omitempty"`
}

// Validate validates this oracle params
func (m *OracleParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OracleParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OracleParams) UnmarshalBinary(b []byte) error {
	var res OracleParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
