// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PrevoteReq prevote req
//
// swagger:model PrevoteReq
type PrevoteReq struct {

	// base req
	BaseReq *BaseReq `json:"base_req,omitempty"`

	// exchange rate of Luna in denom currency is to make provte hash; this field is required to submit prevote in case absense of hash
	ExchangeRate float64 `json:"exchange_rate,omitempty"`

	// hex string; hash of next vote; empty == skip prevote
	Hash string `json:"hash,omitempty"`

	// salt is to make prevote hash; this field is required to submit prevote in case  absense of hash
	Salt string `json:"salt,omitempty"`

	// validator
	Validator ValidatorAddress `json:"validator,omitempty"`
}

// Validate validates this prevote req
func (m *PrevoteReq) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBaseReq(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValidator(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PrevoteReq) validateBaseReq(formats strfmt.Registry) error {

	if swag.IsZero(m.BaseReq) { // not required
		return nil
	}

	if m.BaseReq != nil {
		if err := m.BaseReq.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("base_req")
			}
			return err
		}
	}

	return nil
}

func (m *PrevoteReq) validateValidator(formats strfmt.Registry) error {

	if swag.IsZero(m.Validator) { // not required
		return nil
	}

	if err := m.Validator.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("validator")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PrevoteReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PrevoteReq) UnmarshalBinary(b []byte) error {
	var res PrevoteReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
