// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Proposer proposer
//
// swagger:model Proposer
type Proposer struct {

	// proposal id
	ProposalID string `json:"proposal_id,omitempty"`

	// proposer
	Proposer string `json:"proposer,omitempty"`
}

// Validate validates this proposer
func (m *Proposer) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Proposer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Proposer) UnmarshalBinary(b []byte) error {
	var res Proposer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
