// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UnsignedStdTx unsigned std tx
//
// swagger:model UnsignedStdTx
type UnsignedStdTx struct {

	// fee
	Fee *UnsignedStdTxFee `json:"fee,omitempty"`

	// memo
	Memo string `json:"memo,omitempty"`

	// msg
	Msg []*Msg `json:"msg"`

	// signatures
	Signatures string `json:"signatures,omitempty"`
}

// Validate validates this unsigned std tx
func (m *UnsignedStdTx) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFee(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMsg(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UnsignedStdTx) validateFee(formats strfmt.Registry) error {

	if swag.IsZero(m.Fee) { // not required
		return nil
	}

	if m.Fee != nil {
		if err := m.Fee.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("fee")
			}
			return err
		}
	}

	return nil
}

func (m *UnsignedStdTx) validateMsg(formats strfmt.Registry) error {

	if swag.IsZero(m.Msg) { // not required
		return nil
	}

	for i := 0; i < len(m.Msg); i++ {
		if swag.IsZero(m.Msg[i]) { // not required
			continue
		}

		if m.Msg[i] != nil {
			if err := m.Msg[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("msg" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *UnsignedStdTx) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UnsignedStdTx) UnmarshalBinary(b []byte) error {
	var res UnsignedStdTx
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// UnsignedStdTxFee unsigned std tx fee
//
// swagger:model UnsignedStdTxFee
type UnsignedStdTxFee struct {

	// amount
	Amount []*Coin `json:"amount"`

	// gas
	Gas string `json:"gas,omitempty"`
}

// Validate validates this unsigned std tx fee
func (m *UnsignedStdTxFee) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UnsignedStdTxFee) validateAmount(formats strfmt.Registry) error {

	if swag.IsZero(m.Amount) { // not required
		return nil
	}

	for i := 0; i < len(m.Amount); i++ {
		if swag.IsZero(m.Amount[i]) { // not required
			continue
		}

		if m.Amount[i] != nil {
			if err := m.Amount[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("fee" + "." + "amount" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *UnsignedStdTxFee) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UnsignedStdTxFee) UnmarshalBinary(b []byte) error {
	var res UnsignedStdTxFee
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
