// Code generated by go-swagger; DO NOT EDIT.

package treasury

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetTreasuryTaxCapDenomReader is a Reader for the GetTreasuryTaxCapDenom structure.
type GetTreasuryTaxCapDenomReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTreasuryTaxCapDenomReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTreasuryTaxCapDenomOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetTreasuryTaxCapDenomNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTreasuryTaxCapDenomOK creates a GetTreasuryTaxCapDenomOK with default headers values
func NewGetTreasuryTaxCapDenomOK() *GetTreasuryTaxCapDenomOK {
	return &GetTreasuryTaxCapDenomOK{}
}

/*GetTreasuryTaxCapDenomOK handles this case with default header values.

OK
*/
type GetTreasuryTaxCapDenomOK struct {
	Payload int64
}

func (o *GetTreasuryTaxCapDenomOK) Error() string {
	return fmt.Sprintf("[GET /treasury/tax_cap/{denom}][%d] getTreasuryTaxCapDenomOK  %+v", 200, o.Payload)
}

func (o *GetTreasuryTaxCapDenomOK) GetPayload() int64 {
	return o.Payload
}

func (o *GetTreasuryTaxCapDenomOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTreasuryTaxCapDenomNotFound creates a GetTreasuryTaxCapDenomNotFound with default headers values
func NewGetTreasuryTaxCapDenomNotFound() *GetTreasuryTaxCapDenomNotFound {
	return &GetTreasuryTaxCapDenomNotFound{}
}

/*GetTreasuryTaxCapDenomNotFound handles this case with default header values.

Not Found
*/
type GetTreasuryTaxCapDenomNotFound struct {
}

func (o *GetTreasuryTaxCapDenomNotFound) Error() string {
	return fmt.Sprintf("[GET /treasury/tax_cap/{denom}][%d] getTreasuryTaxCapDenomNotFound ", 404)
}

func (o *GetTreasuryTaxCapDenomNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
