// Code generated by go-swagger; DO NOT EDIT.

package treasury

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTreasuryParametersParams creates a new GetTreasuryParametersParams object
// with the default values initialized.
func NewGetTreasuryParametersParams() *GetTreasuryParametersParams {

	return &GetTreasuryParametersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTreasuryParametersParamsWithTimeout creates a new GetTreasuryParametersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTreasuryParametersParamsWithTimeout(timeout time.Duration) *GetTreasuryParametersParams {

	return &GetTreasuryParametersParams{

		timeout: timeout,
	}
}

// NewGetTreasuryParametersParamsWithContext creates a new GetTreasuryParametersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTreasuryParametersParamsWithContext(ctx context.Context) *GetTreasuryParametersParams {

	return &GetTreasuryParametersParams{

		Context: ctx,
	}
}

// NewGetTreasuryParametersParamsWithHTTPClient creates a new GetTreasuryParametersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTreasuryParametersParamsWithHTTPClient(client *http.Client) *GetTreasuryParametersParams {

	return &GetTreasuryParametersParams{
		HTTPClient: client,
	}
}

/*GetTreasuryParametersParams contains all the parameters to send to the API endpoint
for the get treasury parameters operation typically these are written to a http.Request
*/
type GetTreasuryParametersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get treasury parameters params
func (o *GetTreasuryParametersParams) WithTimeout(timeout time.Duration) *GetTreasuryParametersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get treasury parameters params
func (o *GetTreasuryParametersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get treasury parameters params
func (o *GetTreasuryParametersParams) WithContext(ctx context.Context) *GetTreasuryParametersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get treasury parameters params
func (o *GetTreasuryParametersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get treasury parameters params
func (o *GetTreasuryParametersParams) WithHTTPClient(client *http.Client) *GetTreasuryParametersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get treasury parameters params
func (o *GetTreasuryParametersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetTreasuryParametersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
