// Code generated by go-swagger; DO NOT EDIT.

package treasury

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTreasuryRewardWeightParams creates a new GetTreasuryRewardWeightParams object
// with the default values initialized.
func NewGetTreasuryRewardWeightParams() *GetTreasuryRewardWeightParams {

	return &GetTreasuryRewardWeightParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTreasuryRewardWeightParamsWithTimeout creates a new GetTreasuryRewardWeightParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTreasuryRewardWeightParamsWithTimeout(timeout time.Duration) *GetTreasuryRewardWeightParams {

	return &GetTreasuryRewardWeightParams{

		timeout: timeout,
	}
}

// NewGetTreasuryRewardWeightParamsWithContext creates a new GetTreasuryRewardWeightParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTreasuryRewardWeightParamsWithContext(ctx context.Context) *GetTreasuryRewardWeightParams {

	return &GetTreasuryRewardWeightParams{

		Context: ctx,
	}
}

// NewGetTreasuryRewardWeightParamsWithHTTPClient creates a new GetTreasuryRewardWeightParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTreasuryRewardWeightParamsWithHTTPClient(client *http.Client) *GetTreasuryRewardWeightParams {

	return &GetTreasuryRewardWeightParams{
		HTTPClient: client,
	}
}

/*GetTreasuryRewardWeightParams contains all the parameters to send to the API endpoint
for the get treasury reward weight operation typically these are written to a http.Request
*/
type GetTreasuryRewardWeightParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get treasury reward weight params
func (o *GetTreasuryRewardWeightParams) WithTimeout(timeout time.Duration) *GetTreasuryRewardWeightParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get treasury reward weight params
func (o *GetTreasuryRewardWeightParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get treasury reward weight params
func (o *GetTreasuryRewardWeightParams) WithContext(ctx context.Context) *GetTreasuryRewardWeightParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get treasury reward weight params
func (o *GetTreasuryRewardWeightParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get treasury reward weight params
func (o *GetTreasuryRewardWeightParams) WithHTTPClient(client *http.Client) *GetTreasuryRewardWeightParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get treasury reward weight params
func (o *GetTreasuryRewardWeightParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetTreasuryRewardWeightParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
