// Code generated by go-swagger; DO NOT EDIT.

package authorization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/terra-project/mantle-sdk/lcd/models"
)

// GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeReader is a Reader for the GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgType structure.
type GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOK creates a GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOK with default headers values
func NewGetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOK() *GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOK {
	return &GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOK{}
}

/*GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOK handles this case with default header values.

grant information (one of GenericGrantInfo and SendGrantInfo)
*/
type GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOK struct {
	Payload *GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOKBody
}

func (o *GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOK) Error() string {
	return fmt.Sprintf("[GET /msgauth/granters/{granterAddress}/grantees/{granteeAddress}/grants/{msgType}][%d] getMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOK  %+v", 200, o.Payload)
}

func (o *GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOK) GetPayload() *GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOKBody {
	return o.Payload
}

func (o *GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOKBody get msgauth granters granter address grantees grantee address grants msg type o k body
swagger:model GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOKBody
*/
type GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOKBody struct {

	// generic grant info
	GenericGrantInfo *models.GenericGrantInfo `json:"GenericGrantInfo,omitempty"`

	// send grant info
	SendGrantInfo *models.SendGrantInfo `json:"SendGrantInfo,omitempty"`
}

// Validate validates this get msgauth granters granter address grantees grantee address grants msg type o k body
func (o *GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateGenericGrantInfo(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateSendGrantInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOKBody) validateGenericGrantInfo(formats strfmt.Registry) error {

	if swag.IsZero(o.GenericGrantInfo) { // not required
		return nil
	}

	if o.GenericGrantInfo != nil {
		if err := o.GenericGrantInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOK" + "." + "GenericGrantInfo")
			}
			return err
		}
	}

	return nil
}

func (o *GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOKBody) validateSendGrantInfo(formats strfmt.Registry) error {

	if swag.IsZero(o.SendGrantInfo) { // not required
		return nil
	}

	if o.SendGrantInfo != nil {
		if err := o.SendGrantInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOK" + "." + "SendGrantInfo")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOKBody) UnmarshalBinary(b []byte) error {
	var res GetMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
