// Code generated by go-swagger; DO NOT EDIT.

package authorization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/terra-project/mantle-sdk/lcd/models"
)

// NewPostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams creates a new PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams object
// with the default values initialized.
func NewPostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams() *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams {
	var ()
	return &PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParamsWithTimeout creates a new PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParamsWithTimeout(timeout time.Duration) *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams {
	var ()
	return &PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams{

		timeout: timeout,
	}
}

// NewPostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParamsWithContext creates a new PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParamsWithContext(ctx context.Context) *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams {
	var ()
	return &PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams{

		Context: ctx,
	}
}

// NewPostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParamsWithHTTPClient creates a new PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParamsWithHTTPClient(client *http.Client) *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams {
	var ()
	return &PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams{
		HTTPClient: client,
	}
}

/*PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams contains all the parameters to send to the API endpoint
for the post msgauth granters granter address grantees grantee address grants msg type operation typically these are written to a http.Request
*/
type PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams struct {

	/*GrantRequestBody*/
	GrantRequestBody *models.GrantReq
	/*GranteeAddress*/
	GranteeAddress string
	/*GranterAddress*/
	GranterAddress string
	/*MsgType*/
	MsgType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post msgauth granters granter address grantees grantee address grants msg type params
func (o *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams) WithTimeout(timeout time.Duration) *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post msgauth granters granter address grantees grantee address grants msg type params
func (o *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post msgauth granters granter address grantees grantee address grants msg type params
func (o *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams) WithContext(ctx context.Context) *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post msgauth granters granter address grantees grantee address grants msg type params
func (o *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post msgauth granters granter address grantees grantee address grants msg type params
func (o *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams) WithHTTPClient(client *http.Client) *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post msgauth granters granter address grantees grantee address grants msg type params
func (o *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGrantRequestBody adds the grantRequestBody to the post msgauth granters granter address grantees grantee address grants msg type params
func (o *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams) WithGrantRequestBody(grantRequestBody *models.GrantReq) *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams {
	o.SetGrantRequestBody(grantRequestBody)
	return o
}

// SetGrantRequestBody adds the grantRequestBody to the post msgauth granters granter address grantees grantee address grants msg type params
func (o *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams) SetGrantRequestBody(grantRequestBody *models.GrantReq) {
	o.GrantRequestBody = grantRequestBody
}

// WithGranteeAddress adds the granteeAddress to the post msgauth granters granter address grantees grantee address grants msg type params
func (o *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams) WithGranteeAddress(granteeAddress string) *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams {
	o.SetGranteeAddress(granteeAddress)
	return o
}

// SetGranteeAddress adds the granteeAddress to the post msgauth granters granter address grantees grantee address grants msg type params
func (o *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams) SetGranteeAddress(granteeAddress string) {
	o.GranteeAddress = granteeAddress
}

// WithGranterAddress adds the granterAddress to the post msgauth granters granter address grantees grantee address grants msg type params
func (o *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams) WithGranterAddress(granterAddress string) *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams {
	o.SetGranterAddress(granterAddress)
	return o
}

// SetGranterAddress adds the granterAddress to the post msgauth granters granter address grantees grantee address grants msg type params
func (o *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams) SetGranterAddress(granterAddress string) {
	o.GranterAddress = granterAddress
}

// WithMsgType adds the msgType to the post msgauth granters granter address grantees grantee address grants msg type params
func (o *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams) WithMsgType(msgType string) *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams {
	o.SetMsgType(msgType)
	return o
}

// SetMsgType adds the msgType to the post msgauth granters granter address grantees grantee address grants msg type params
func (o *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams) SetMsgType(msgType string) {
	o.MsgType = msgType
}

// WriteToRequest writes these params to a swagger request
func (o *PostMsgauthGrantersGranterAddressGranteesGranteeAddressGrantsMsgTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.GrantRequestBody != nil {
		if err := r.SetBodyParam(o.GrantRequestBody); err != nil {
			return err
		}
	}

	// path param granteeAddress
	if err := r.SetPathParam("granteeAddress", o.GranteeAddress); err != nil {
		return err
	}

	// path param granterAddress
	if err := r.SetPathParam("granterAddress", o.GranterAddress); err != nil {
		return err
	}

	// path param msgType
	if err := r.SetPathParam("msgType", o.MsgType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
